# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/ignis/HDD/Repositories/MarkovPasswords

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/ignis/HDD/Repositories/MarkovPasswords

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ignis/HDD/Repositories/MarkovPasswords/CMakeFiles /media/ignis/HDD/Repositories/MarkovPasswords/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/ignis/HDD/Repositories/MarkovPasswords/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cudamarkopy

# Build rule for target.
cudamarkopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudamarkopy
.PHONY : cudamarkopy

# fast build rule for target.
cudamarkopy/fast:
	$(MAKE) -f CMakeFiles/cudamarkopy.dir/build.make CMakeFiles/cudamarkopy.dir/build
.PHONY : cudamarkopy/fast

#=============================================================================
# Target rules for targets named cudamarkov_test

# Build rule for target.
cudamarkov_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudamarkov_test
.PHONY : cudamarkov_test

# fast build rule for target.
cudamarkov_test/fast:
	$(MAKE) -f CMakeFiles/cudamarkov_test.dir/build.make CMakeFiles/cudamarkov_test.dir/build
.PHONY : cudamarkov_test/fast

#=============================================================================
# Target rules for targets named cudamarkov

# Build rule for target.
cudamarkov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cudamarkov
.PHONY : cudamarkov

# fast build rule for target.
cudamarkov/fast:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/build
.PHONY : cudamarkov/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named markopy

# Build rule for target.
markopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markopy
.PHONY : markopy

# fast build rule for target.
markopy/fast:
	$(MAKE) -f CMakeFiles/markopy.dir/build.make CMakeFiles/markopy.dir/build
.PHONY : markopy/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named markovp

# Build rule for target.
markovp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markovp
.PHONY : markovp

# fast build rule for target.
markovp/fast:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/build
.PHONY : markovp/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named markov

# Build rule for target.
markov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markov
.PHONY : markov

# fast build rule for target.
markov/fast:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/build
.PHONY : markov/fast

CudaMarkopy/src/Module/cudaMarkopy.o: CudaMarkopy/src/Module/cudaMarkopy.cu.o

.PHONY : CudaMarkopy/src/Module/cudaMarkopy.o

# target to build an object file
CudaMarkopy/src/Module/cudaMarkopy.cu.o:
	$(MAKE) -f CMakeFiles/cudamarkopy.dir/build.make CMakeFiles/cudamarkopy.dir/CudaMarkopy/src/Module/cudaMarkopy.cu.o
.PHONY : CudaMarkopy/src/Module/cudaMarkopy.cu.o

CudaMarkopy/src/Module/cudaMarkopy.i: CudaMarkopy/src/Module/cudaMarkopy.cu.i

.PHONY : CudaMarkopy/src/Module/cudaMarkopy.i

# target to preprocess a source file
CudaMarkopy/src/Module/cudaMarkopy.cu.i:
	$(MAKE) -f CMakeFiles/cudamarkopy.dir/build.make CMakeFiles/cudamarkopy.dir/CudaMarkopy/src/Module/cudaMarkopy.cu.i
.PHONY : CudaMarkopy/src/Module/cudaMarkopy.cu.i

CudaMarkopy/src/Module/cudaMarkopy.s: CudaMarkopy/src/Module/cudaMarkopy.cu.s

.PHONY : CudaMarkopy/src/Module/cudaMarkopy.s

# target to generate assembly for a file
CudaMarkopy/src/Module/cudaMarkopy.cu.s:
	$(MAKE) -f CMakeFiles/cudamarkopy.dir/build.make CMakeFiles/cudamarkopy.dir/CudaMarkopy/src/Module/cudaMarkopy.cu.s
.PHONY : CudaMarkopy/src/Module/cudaMarkopy.cu.s

CudaMarkovAPI/src/cudaDeviceController.o: CudaMarkovAPI/src/cudaDeviceController.cu.o

.PHONY : CudaMarkovAPI/src/cudaDeviceController.o

# target to build an object file
CudaMarkovAPI/src/cudaDeviceController.cu.o:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaDeviceController.cu.o
.PHONY : CudaMarkovAPI/src/cudaDeviceController.cu.o

CudaMarkovAPI/src/cudaDeviceController.i: CudaMarkovAPI/src/cudaDeviceController.cu.i

.PHONY : CudaMarkovAPI/src/cudaDeviceController.i

# target to preprocess a source file
CudaMarkovAPI/src/cudaDeviceController.cu.i:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaDeviceController.cu.i
.PHONY : CudaMarkovAPI/src/cudaDeviceController.cu.i

CudaMarkovAPI/src/cudaDeviceController.s: CudaMarkovAPI/src/cudaDeviceController.cu.s

.PHONY : CudaMarkovAPI/src/cudaDeviceController.s

# target to generate assembly for a file
CudaMarkovAPI/src/cudaDeviceController.cu.s:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaDeviceController.cu.s
.PHONY : CudaMarkovAPI/src/cudaDeviceController.cu.s

CudaMarkovAPI/src/cudaModelMatrix.o: CudaMarkovAPI/src/cudaModelMatrix.cu.o

.PHONY : CudaMarkovAPI/src/cudaModelMatrix.o

# target to build an object file
CudaMarkovAPI/src/cudaModelMatrix.cu.o:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaModelMatrix.cu.o
.PHONY : CudaMarkovAPI/src/cudaModelMatrix.cu.o

CudaMarkovAPI/src/cudaModelMatrix.i: CudaMarkovAPI/src/cudaModelMatrix.cu.i

.PHONY : CudaMarkovAPI/src/cudaModelMatrix.i

# target to preprocess a source file
CudaMarkovAPI/src/cudaModelMatrix.cu.i:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaModelMatrix.cu.i
.PHONY : CudaMarkovAPI/src/cudaModelMatrix.cu.i

CudaMarkovAPI/src/cudaModelMatrix.s: CudaMarkovAPI/src/cudaModelMatrix.cu.s

.PHONY : CudaMarkovAPI/src/cudaModelMatrix.s

# target to generate assembly for a file
CudaMarkovAPI/src/cudaModelMatrix.cu.s:
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/cudaModelMatrix.cu.s
.PHONY : CudaMarkovAPI/src/cudaModelMatrix.cu.s

CudaMarkovAPI/src/main.o: CudaMarkovAPI/src/main.cu.o

.PHONY : CudaMarkovAPI/src/main.o

# target to build an object file
CudaMarkovAPI/src/main.cu.o:
	$(MAKE) -f CMakeFiles/cudamarkov_test.dir/build.make CMakeFiles/cudamarkov_test.dir/CudaMarkovAPI/src/main.cu.o
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/main.cu.o
.PHONY : CudaMarkovAPI/src/main.cu.o

CudaMarkovAPI/src/main.i: CudaMarkovAPI/src/main.cu.i

.PHONY : CudaMarkovAPI/src/main.i

# target to preprocess a source file
CudaMarkovAPI/src/main.cu.i:
	$(MAKE) -f CMakeFiles/cudamarkov_test.dir/build.make CMakeFiles/cudamarkov_test.dir/CudaMarkovAPI/src/main.cu.i
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/main.cu.i
.PHONY : CudaMarkovAPI/src/main.cu.i

CudaMarkovAPI/src/main.s: CudaMarkovAPI/src/main.cu.s

.PHONY : CudaMarkovAPI/src/main.s

# target to generate assembly for a file
CudaMarkovAPI/src/main.cu.s:
	$(MAKE) -f CMakeFiles/cudamarkov_test.dir/build.make CMakeFiles/cudamarkov_test.dir/CudaMarkovAPI/src/main.cu.s
	$(MAKE) -f CMakeFiles/cudamarkov.dir/build.make CMakeFiles/cudamarkov.dir/CudaMarkovAPI/src/main.cu.s
.PHONY : CudaMarkovAPI/src/main.cu.s

Markopy/src/Module/markopy.o: Markopy/src/Module/markopy.cpp.o

.PHONY : Markopy/src/Module/markopy.o

# target to build an object file
Markopy/src/Module/markopy.cpp.o:
	$(MAKE) -f CMakeFiles/markopy.dir/build.make CMakeFiles/markopy.dir/Markopy/src/Module/markopy.cpp.o
.PHONY : Markopy/src/Module/markopy.cpp.o

Markopy/src/Module/markopy.i: Markopy/src/Module/markopy.cpp.i

.PHONY : Markopy/src/Module/markopy.i

# target to preprocess a source file
Markopy/src/Module/markopy.cpp.i:
	$(MAKE) -f CMakeFiles/markopy.dir/build.make CMakeFiles/markopy.dir/Markopy/src/Module/markopy.cpp.i
.PHONY : Markopy/src/Module/markopy.cpp.i

Markopy/src/Module/markopy.s: Markopy/src/Module/markopy.cpp.s

.PHONY : Markopy/src/Module/markopy.s

# target to generate assembly for a file
Markopy/src/Module/markopy.cpp.s:
	$(MAKE) -f CMakeFiles/markopy.dir/build.make CMakeFiles/markopy.dir/Markopy/src/Module/markopy.cpp.s
.PHONY : Markopy/src/Module/markopy.cpp.s

MarkovAPI/src/markovPasswords.o: MarkovAPI/src/markovPasswords.cpp.o

.PHONY : MarkovAPI/src/markovPasswords.o

# target to build an object file
MarkovAPI/src/markovPasswords.cpp.o:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/markovPasswords.cpp.o
.PHONY : MarkovAPI/src/markovPasswords.cpp.o

MarkovAPI/src/markovPasswords.i: MarkovAPI/src/markovPasswords.cpp.i

.PHONY : MarkovAPI/src/markovPasswords.i

# target to preprocess a source file
MarkovAPI/src/markovPasswords.cpp.i:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/markovPasswords.cpp.i
.PHONY : MarkovAPI/src/markovPasswords.cpp.i

MarkovAPI/src/markovPasswords.s: MarkovAPI/src/markovPasswords.cpp.s

.PHONY : MarkovAPI/src/markovPasswords.s

# target to generate assembly for a file
MarkovAPI/src/markovPasswords.cpp.s:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/markovPasswords.cpp.s
.PHONY : MarkovAPI/src/markovPasswords.cpp.s

MarkovAPI/src/modelMatrix.o: MarkovAPI/src/modelMatrix.cpp.o

.PHONY : MarkovAPI/src/modelMatrix.o

# target to build an object file
MarkovAPI/src/modelMatrix.cpp.o:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/modelMatrix.cpp.o
.PHONY : MarkovAPI/src/modelMatrix.cpp.o

MarkovAPI/src/modelMatrix.i: MarkovAPI/src/modelMatrix.cpp.i

.PHONY : MarkovAPI/src/modelMatrix.i

# target to preprocess a source file
MarkovAPI/src/modelMatrix.cpp.i:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/modelMatrix.cpp.i
.PHONY : MarkovAPI/src/modelMatrix.cpp.i

MarkovAPI/src/modelMatrix.s: MarkovAPI/src/modelMatrix.cpp.s

.PHONY : MarkovAPI/src/modelMatrix.s

# target to generate assembly for a file
MarkovAPI/src/modelMatrix.cpp.s:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/modelMatrix.cpp.s
.PHONY : MarkovAPI/src/modelMatrix.cpp.s

MarkovAPI/src/threadSharedListHandler.o: MarkovAPI/src/threadSharedListHandler.cpp.o

.PHONY : MarkovAPI/src/threadSharedListHandler.o

# target to build an object file
MarkovAPI/src/threadSharedListHandler.cpp.o:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/threadSharedListHandler.cpp.o
.PHONY : MarkovAPI/src/threadSharedListHandler.cpp.o

MarkovAPI/src/threadSharedListHandler.i: MarkovAPI/src/threadSharedListHandler.cpp.i

.PHONY : MarkovAPI/src/threadSharedListHandler.i

# target to preprocess a source file
MarkovAPI/src/threadSharedListHandler.cpp.i:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/threadSharedListHandler.cpp.i
.PHONY : MarkovAPI/src/threadSharedListHandler.cpp.i

MarkovAPI/src/threadSharedListHandler.s: MarkovAPI/src/threadSharedListHandler.cpp.s

.PHONY : MarkovAPI/src/threadSharedListHandler.s

# target to generate assembly for a file
MarkovAPI/src/threadSharedListHandler.cpp.s:
	$(MAKE) -f CMakeFiles/markov.dir/build.make CMakeFiles/markov.dir/MarkovAPI/src/threadSharedListHandler.cpp.s
.PHONY : MarkovAPI/src/threadSharedListHandler.cpp.s

MarkovPasswords/src/argparse.o: MarkovPasswords/src/argparse.cpp.o

.PHONY : MarkovPasswords/src/argparse.o

# target to build an object file
MarkovPasswords/src/argparse.cpp.o:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/argparse.cpp.o
.PHONY : MarkovPasswords/src/argparse.cpp.o

MarkovPasswords/src/argparse.i: MarkovPasswords/src/argparse.cpp.i

.PHONY : MarkovPasswords/src/argparse.i

# target to preprocess a source file
MarkovPasswords/src/argparse.cpp.i:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/argparse.cpp.i
.PHONY : MarkovPasswords/src/argparse.cpp.i

MarkovPasswords/src/argparse.s: MarkovPasswords/src/argparse.cpp.s

.PHONY : MarkovPasswords/src/argparse.s

# target to generate assembly for a file
MarkovPasswords/src/argparse.cpp.s:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/argparse.cpp.s
.PHONY : MarkovPasswords/src/argparse.cpp.s

MarkovPasswords/src/color/term.o: MarkovPasswords/src/color/term.cpp.o

.PHONY : MarkovPasswords/src/color/term.o

# target to build an object file
MarkovPasswords/src/color/term.cpp.o:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/color/term.cpp.o
.PHONY : MarkovPasswords/src/color/term.cpp.o

MarkovPasswords/src/color/term.i: MarkovPasswords/src/color/term.cpp.i

.PHONY : MarkovPasswords/src/color/term.i

# target to preprocess a source file
MarkovPasswords/src/color/term.cpp.i:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/color/term.cpp.i
.PHONY : MarkovPasswords/src/color/term.cpp.i

MarkovPasswords/src/color/term.s: MarkovPasswords/src/color/term.cpp.s

.PHONY : MarkovPasswords/src/color/term.s

# target to generate assembly for a file
MarkovPasswords/src/color/term.cpp.s:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/color/term.cpp.s
.PHONY : MarkovPasswords/src/color/term.cpp.s

MarkovPasswords/src/main.o: MarkovPasswords/src/main.cpp.o

.PHONY : MarkovPasswords/src/main.o

# target to build an object file
MarkovPasswords/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/main.cpp.o
.PHONY : MarkovPasswords/src/main.cpp.o

MarkovPasswords/src/main.i: MarkovPasswords/src/main.cpp.i

.PHONY : MarkovPasswords/src/main.i

# target to preprocess a source file
MarkovPasswords/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/main.cpp.i
.PHONY : MarkovPasswords/src/main.cpp.i

MarkovPasswords/src/main.s: MarkovPasswords/src/main.cpp.s

.PHONY : MarkovPasswords/src/main.s

# target to generate assembly for a file
MarkovPasswords/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/markovp.dir/build.make CMakeFiles/markovp.dir/MarkovPasswords/src/main.cpp.s
.PHONY : MarkovPasswords/src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... cudamarkopy"
	@echo "... rebuild_cache"
	@echo "... cudamarkov_test"
	@echo "... cudamarkov"
	@echo "... edit_cache"
	@echo "... NightlyMemCheck"
	@echo "... NightlyTest"
	@echo "... ContinuousConfigure"
	@echo "... markopy"
	@echo "... ContinuousBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyMemoryCheck"
	@echo "... ExperimentalTest"
	@echo "... ContinuousUpdate"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... Experimental"
	@echo "... ContinuousCoverage"
	@echo "... ExperimentalConfigure"
	@echo "... Continuous"
	@echo "... Nightly"
	@echo "... NightlySubmit"
	@echo "... NightlyStart"
	@echo "... ExperimentalCoverage"
	@echo "... markovp"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalStart"
	@echo "... NightlyBuild"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousStart"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousTest"
	@echo "... ContinuousSubmit"
	@echo "... markov"
	@echo "... CudaMarkopy/src/Module/cudaMarkopy.o"
	@echo "... CudaMarkopy/src/Module/cudaMarkopy.i"
	@echo "... CudaMarkopy/src/Module/cudaMarkopy.s"
	@echo "... CudaMarkovAPI/src/cudaDeviceController.o"
	@echo "... CudaMarkovAPI/src/cudaDeviceController.i"
	@echo "... CudaMarkovAPI/src/cudaDeviceController.s"
	@echo "... CudaMarkovAPI/src/cudaModelMatrix.o"
	@echo "... CudaMarkovAPI/src/cudaModelMatrix.i"
	@echo "... CudaMarkovAPI/src/cudaModelMatrix.s"
	@echo "... CudaMarkovAPI/src/main.o"
	@echo "... CudaMarkovAPI/src/main.i"
	@echo "... CudaMarkovAPI/src/main.s"
	@echo "... Markopy/src/Module/markopy.o"
	@echo "... Markopy/src/Module/markopy.i"
	@echo "... Markopy/src/Module/markopy.s"
	@echo "... MarkovAPI/src/markovPasswords.o"
	@echo "... MarkovAPI/src/markovPasswords.i"
	@echo "... MarkovAPI/src/markovPasswords.s"
	@echo "... MarkovAPI/src/modelMatrix.o"
	@echo "... MarkovAPI/src/modelMatrix.i"
	@echo "... MarkovAPI/src/modelMatrix.s"
	@echo "... MarkovAPI/src/threadSharedListHandler.o"
	@echo "... MarkovAPI/src/threadSharedListHandler.i"
	@echo "... MarkovAPI/src/threadSharedListHandler.s"
	@echo "... MarkovPasswords/src/argparse.o"
	@echo "... MarkovPasswords/src/argparse.i"
	@echo "... MarkovPasswords/src/argparse.s"
	@echo "... MarkovPasswords/src/color/term.o"
	@echo "... MarkovPasswords/src/color/term.i"
	@echo "... MarkovPasswords/src/color/term.s"
	@echo "... MarkovPasswords/src/main.o"
	@echo "... MarkovPasswords/src/main.i"
	@echo "... MarkovPasswords/src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

