Markopy/MarkovAPICLI/src/main.cpp File Reference
Test cases for Markov::API::ModelMatrix.
#include <iostream>
#include `color/term.h`
#include `argparse.h`
#include <string>
#include <cstring>
#include <sstream>
#include `MarkovAPI/src/markovPasswords.h`
#include `MarkovAPI/src/modelMatrix.h`
#include <chrono>
Functions
int main (int argc, char **argv)
Launch CLI tool.
Detailed Description
Test cases for Markov::API::ModelMatrix.
Authors
Ata Hakçıl, Celal Sahir Çetiner
Parse command line arguements.
Class to flatten and reduce Markov::Model to a Matrix. Matrix level operations can be used for Generation events, with a significant performance optimization at the cost of O(N) memory complexity (O(1) memory space for slow mode)
To limit the maximum memory usage, each generation operation is partitioned into 50M chunks for allocation. Threads are sychronized and files are flushed every 50M operations.
Markov::Model with char represented nodes. Includes wrappers for Markov::Model and additional helper functions to handle file I/O
This class is an extension of Markov::Model<char>, with higher level abstractions such as train and generate.
Definition in file main.cpp.
Function Documentation
main()
int main (int argc, char ** argv)
Launch CLI tool.
Definition at line 23 of file main.cpp.
                                {
    Markov::API::CLI::Terminal t;
    /*
    ProgramOptions* p = Argparse::parse(argc, argv);
    if (p==0 || p->bFailure) {
        std::cout << TERM_FAIL << "Arguments Failed to Parse" << std::endl;
        Argparse::help();
    }*/
    Markov::API::CLI::Argparse a(argc,argv);
    Markov::API::ModelMatrix markovPass;
    std::cerr << "Importing model.\n";
    markovPass.Import("models/finished.mdl");
    std::cerr << "Import done. \n";
    markovPass.Buff("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~", 100);
    
    markovPass.Export("models/buffed-symbols-100fold.mdl");
    //markovPass.ConstructMatrix();
    //std::chrono::steady_clock::time_point begin = std::chrono::steady_clock::now();
    //markovPass.FastRandomWalk(50000000,"/media/ignis/Stuff/wordlist.txt",6,12,25, true);
    //markovPass.FastRandomWalk(500000000,"/media/ignis/Stuff/wordlist2.txt",6,12,25, true);
    //std::chrono::steady_clock::time_point end = std::chrono::steady_clock::now();
    //std::cerr << "Finished in:" << std::chrono::duration_cast<std::chrono::milliseconds> (end - begin).count() << " milliseconds" << std::endl;
    return 0;
}
References Markov::API::CLI::Argparse::Argparse(), Markov::API::MarkovPasswords::Buff(), Markov::Model< NodeStorageType >::Export(), and Markov::API::ModelMatrix::Import().