Markov::GUI::CLI Class Reference
QT CLI Class.
#include <CLI.h>
Public Slots
void start ()
void statistics ()
void about ()
Public Member Functions
CLI (QWidget *parent=Q_NULLPTR)
Private Attributes
Ui::CLI ui
Detailed Description
QT CLI Class.
Definition at line 14 of file CLI.h.
Constructor & Destructor Documentation
CLI()
Markov::GUI::CLI::CLI (QWidget * parent = Q_NULLPTR)
Definition at line 15 of file CLI.cpp.
    : QMainWindow(parent)
{
    ui.setupUi(this);
    QObject::connect(ui.startButton, &QPushButton::clicked, this, [this] {start(); });
    QObject::connect(ui.commandLinkButton_2, &QPushButton::clicked, this, [this] {statistics(); });
    QObject::connect(ui.commandLinkButton, &QPushButton::clicked, this, [this] {about(); });
     
}
References about(), start(), statistics(), and ui.
Member Function Documentation
about
void Markov::GUI::CLI::about () [slot]
Definition at line 36 of file CLI.cpp.
                         {
    /*
    about button
    */
}
Referenced by CLI().
start
void Markov::GUI::CLI::start () [slot]
Definition at line 26 of file CLI.cpp.
                         {
    Train* w = new Train;
    w->show();
    this->close();
}
Referenced by CLI().
statistics
void Markov::GUI::CLI::statistics () [slot]
Definition at line 31 of file CLI.cpp.
                              {
    /*
    statistic will show
    */
}
Referenced by CLI().
Member Data Documentation
ui
Ui::CLI Markov::GUI::CLI::ui [private]
Definition at line 20 of file CLI.h.
Referenced by CLI().
The documentation for this class was generated from the following files:
Markopy/MarkovPasswordsGUI/src/CLI.h
Markopy/MarkovPasswordsGUI/src/CLI.cpp