Python.Markopy.Evaluation.CorpusEvaluator Class Reference
evaluate a corpus
Public Member Functions
None __init__ (self, str filename)
default constructor
def evaluate (self)
def success (self, checkname)
pass a test
def fail (self, checkname)
fail a test
def finalize (self)
Public Attributes
filename
checks
TEST_PASS_SYMBOL
TEST_FAIL_SYMBOL
all_checks_passed
files
check_funcs
Private Member Functions
list _evaluate (self, file)
evaluate a single file.
Detailed Description
evaluate a corpus
Definition at line 238 of file evaluate.py.
Constructor & Destructor Documentation
__init__()
None Python.Markopy.Evaluation.CorpusEvaluator.__init__ (self, str filename)
default constructor
Parameters
filename filename or pattern to check
Reimplemented from Python.Markopy.Evaluation.Evaluator.
Definition at line 244 of file evaluate.py.
    def __init__(self, filename: str) -> None:
        """!
        @brief default constructor
        @param filename filename or pattern to check
        """
        valid = super().__init__(filename)
        if not valid:
            return False
Member Function Documentation
_evaluate()
list Python.Markopy.Evaluation.CorpusEvaluator._evaluate (self, file) [private]
evaluate a single file.
Remove reading file because it should be read line by line.
Parameters
file corpus filename to evaluate
Reimplemented from Python.Markopy.Evaluation.Evaluator.
Definition at line 295 of file evaluate.py.
    def _evaluate(self, file) -> list:
        """!
        @brief evaluate a single file. Remove reading file because it should be read line by line.
        @param file corpus filename to evaluate
        """
        if(not os.path.isfile(file)):
            logging.pprint(f"Given file {file} is not a valid filename")
            return False
        else:
            return True
            
Referenced by Python.Markopy.Evaluation.Evaluator.evaluate().
evaluate()
def Python.Markopy.Evaluation.CorpusEvaluator.evaluate (self)
Reimplemented from Python.Markopy.Evaluation.Evaluator.
Definition at line 253 of file evaluate.py.
    def evaluate(self):
        "! @brief evalute a corpus. Might take a long time"
        logging.pprint("WARNING: This takes a while with larger corpus files", 2)
        logging.VERBOSITY=2
        logging.SHOW_STACK_THRESHOLD=3
        super().evaluate()
        for file in self.files:
            delimiter = ''
            sum=0
            max=0
            total_chars = 0
            lines_count = 0
            bDelimiterConflict=False
            logging.pprint(f"Corpus: {file.split('/')[-1]}: ",2)
            with open(file, "rb") as corpus:
                for line in corpus:
                    lines_count+=1
                    match = re.match(r"([0-9]+)(.)(.*)\n", line.decode()).groups()
                    if(delimiter and delimiter!=match[1]):
                        bDelimiterConflict = True
                        
                    elif(not delimiter):
                        delimiter = match[1]
                        logging.pprint(f"Delimiter is: {delimiter.encode()}")
                    sum +=int(match[0])
                    total_chars += len(match[2])
                    if(int(match[0])>max):
                        max=int(match[0])
                if(bDelimiterConflict):
                    self.fail("Incorrect delimiter found")
                else:
                    self.success("No structural conflicts")
                logging.pprint(f"Total number of lines: {lines_count}")
                logging.pprint(f"Sum of all string weights: {sum}")
                logging.pprint(f"Character total: {total_chars}")
                logging.pprint(f"Average length: {total_chars/lines_count}")
                logging.pprint(f"Average weight: {sum/lines_count}")
            self.finalize()
References Python.Markopy.Evaluation.Evaluator.fail(), Python.Markopy.Evaluation.Evaluator.files, Python.Markopy.Evaluation.Evaluator.finalize(), and Python.Markopy.Evaluation.Evaluator.success().
Referenced by Python.Markopy.MarkopyCLI.parse().
fail()
def Python.Markopy.Evaluation.Evaluator.fail (self, checkname) [inherited]
fail a test
Parameters
checkname text to display with the check
Definition at line 72 of file evaluate.py.
    def fail(self, checkname):
        """!
        @brief fail a test
        @param checkname text to display with the check
        """
        self.all_checks_passed = False
        self.checks.append((checkname, self.TEST_FAIL_SYMBOL))
References Python.Markopy.Evaluation.Evaluator.all_checks_passed, Python.Markopy.Evaluation.Evaluator.checks, and Python.Markopy.Evaluation.Evaluator.TEST_FAIL_SYMBOL.
Referenced by Python.Markopy.Evaluation.ModelEvaluator.check_dangling(), Python.Markopy.Evaluation.ModelEvaluator.check_lean(), Python.Markopy.Evaluation.ModelEvaluator.check_min(), Python.Markopy.Evaluation.ModelEvaluator.check_structure(), and Python.Markopy.Evaluation.CorpusEvaluator.evaluate().
finalize()
def Python.Markopy.Evaluation.Evaluator.finalize (self) [inherited]
Definition at line 81 of file evaluate.py.
    def finalize(self):
        "! @brief finalize an evaluation and print checks"
        print("\n################ Checks ################ ")
        for test in self.checks:
            logging.pprint(f"{test[0]:30}:{test[1]} ")
        print("\n")
        self.checks = []
        return self.all_checks_passed
References Python.Markopy.Evaluation.Evaluator.all_checks_passed, and Python.Markopy.Evaluation.Evaluator.checks.
Referenced by Python.Markopy.Evaluation.CorpusEvaluator.evaluate().
success()
def Python.Markopy.Evaluation.Evaluator.success (self, checkname) [inherited]
pass a test
Parameters
checkname text to display with the check
Definition at line 65 of file evaluate.py.
    def success(self, checkname):
        """!
        @brief pass a test
        @param checkname text to display with the check
        """
        self.checks.append((checkname, self.TEST_PASS_SYMBOL))
References Python.Markopy.Evaluation.Evaluator.checks, and Python.Markopy.Evaluation.Evaluator.TEST_PASS_SYMBOL.
Referenced by Python.Markopy.Evaluation.ModelEvaluator.check_dangling(), Python.Markopy.Evaluation.ModelEvaluator.check_lean(), Python.Markopy.Evaluation.ModelEvaluator.check_min(), Python.Markopy.Evaluation.ModelEvaluator.check_structure(), and Python.Markopy.Evaluation.CorpusEvaluator.evaluate().
Member Data Documentation
all_checks_passed
Python.Markopy.Evaluation.Evaluator.all_checks_passed [inherited]
Definition at line 36 of file evaluate.py.
Referenced by Python.Markopy.Evaluation.Evaluator.fail(), and Python.Markopy.Evaluation.Evaluator.finalize().
check_funcs
Python.Markopy.Evaluation.Evaluator.check_funcs [inherited]
Definition at line 49 of file evaluate.py.
checks
Python.Markopy.Evaluation.Evaluator.checks [inherited]
Definition at line 33 of file evaluate.py.
Referenced by Python.Markopy.Evaluation.Evaluator.fail(), Python.Markopy.Evaluation.Evaluator.finalize(), and Python.Markopy.Evaluation.Evaluator.success().
filename
Python.Markopy.Evaluation.Evaluator.filename [inherited]
Definition at line 32 of file evaluate.py.
files
Python.Markopy.Evaluation.Evaluator.files [inherited]
Definition at line 37 of file evaluate.py.
Referenced by Python.Markopy.Evaluation.Evaluator.evaluate(), Python.Markopy.Evaluation.ModelEvaluator.evaluate(), and Python.Markopy.Evaluation.CorpusEvaluator.evaluate().
TEST_FAIL_SYMBOL
Python.Markopy.Evaluation.Evaluator.TEST_FAIL_SYMBOL [inherited]
Definition at line 35 of file evaluate.py.
Referenced by Python.Markopy.Evaluation.Evaluator.fail().
TEST_PASS_SYMBOL
Python.Markopy.Evaluation.Evaluator.TEST_PASS_SYMBOL [inherited]
Definition at line 34 of file evaluate.py.
Referenced by Python.Markopy.Evaluation.Evaluator.success().
The documentation for this class was generated from the following file:
Markopy/Markopy/src/CLI/evaluate.py