Markov::Random::DefaultRandomEngine Class Reference
Implementation using Random.h default random engine.
#include <random.h>
Public Member Functions
unsigned long random ()
Generate Random Number.
Protected Member Functions
std::random_device & rd ()
Default random device for seeding.
std::default_random_engine & generator ()
Default random engine for seeding.
std::uniform_int_distribution< long long unsigned > & distribution ()
Distribution schema for seeding.
Detailed Description
Implementation using Random.h default random engine.
This engine is also used by other engines for seeding.
Example Use: Using Default Engine with RandomWalk
Markov::Model<char> model;
Model.import("model.mdl");
char* res = new char[11];
Markov::Random::DefaultRandomEngine randomEngine;
for (int i = 0; i < 10; i++) {
    this->RandomWalk(&randomEngine, 5, 10, res);
    std::cout << res << "\n";
 }
Example Use: Generating a random number with Marsaglia Engine
Markov::Random::DefaultRandomEngine de;
std::cout << de.random();
Definition at line 52 of file random.h.
Member Function Documentation
distribution()
std::uniform_int_distribution<long long unsigned>& Markov::Random::DefaultRandomEngine::distribution () [inline], [protected]
Distribution schema for seeding.
Definition at line 81 of file random.h.
                                                                               {
            static std::uniform_int_distribution<long long unsigned> _distribution(0, 0xffffFFFF);
            return _distribution;
        }
Referenced by Markov::Random::Marsaglia::Marsaglia(), and random().
generator()
std::default_random_engine& Markov::Random::DefaultRandomEngine::generator () [inline], [protected]
Default random engine for seeding.
Definition at line 73 of file random.h.
                                                     {
            static std::default_random_engine _generator(rd()());
            return _generator;
        }
References rd().
Referenced by Markov::Random::Marsaglia::Marsaglia(), and random().
random()
unsigned long Markov::Random::DefaultRandomEngine::random () [inline], [virtual]
Generate Random Number.
Returns
random number in long range.
Implements Markov::Random::RandomEngine.
Reimplemented in Markov::Random::Marsaglia.
Definition at line 57 of file random.h.
                                     {
            return this->distribution()(this->generator());
        }
References distribution(), and generator().
rd()
std::random_device& Markov::Random::DefaultRandomEngine::rd () [inline], [protected]
Default random device for seeding.
Definition at line 65 of file random.h.
                                      {
            static std::random_device _rd;
            return _rd;
        }
Referenced by generator().
The documentation for this class was generated from the following file:
random.h