Markov::Edge< NodeStorageType > Class Template Reference
Edge class used to link nodes in the model together.
#include <edge.h>
Public Member Functions
Edge ()
Default constructor.
Edge (Node< NodeStorageType > *_left, Node< NodeStorageType > *_right)
Constructor. Initialize edge with given RightNode and LeftNode.
void AdjustEdge (long int offset)
Adjust the edge EdgeWeight with offset. Adds the offset parameter to the edge EdgeWeight.
Node< NodeStorageType > * TraverseNode ()
Traverse this edge to RightNode.
void SetLeftEdge (Node< NodeStorageType > *)
Set LeftNode of this edge.
void SetRightEdge (Node< NodeStorageType > *)
Set RightNode of this edge.
uint64_t EdgeWeight ()
return edge's EdgeWeight.
Node< NodeStorageType > * LeftNode ()
return edge's LeftNode
Node< NodeStorageType > * RightNode ()
return edge's RightNode
Private Attributes
Node< NodeStorageType > * _left
Node< NodeStorageType > * _right
source node
long int _weight
target node
Detailed Description
template<typename NodeStorageType>
class Markov::Edge< NodeStorageType >
Edge class used to link nodes in the model together.
Has LeftNode, RightNode, and EdgeWeight of the edge. Edges are UNIDIRECTIONAL in this model. They can only be traversed LeftNode to RightNode.
Definition at line 16 of file edge.h.
Constructor & Destructor Documentation
Edge() [1/2]
template<typename NodeStorageType >
Markov::Edge< NodeStorageType >::Edge
Default constructor.
Definition at line 105 of file edge.h.
                                  {
    this->_left = NULL;
    this->_right = NULL;
    this->_weight = 0;
}
Edge() [2/2]
template<typename NodeStorageType >
Markov::Edge< NodeStorageType >::Edge (Markov::Node< NodeStorageType > * _left, Markov::Node< NodeStorageType > * _right)
Constructor. Initialize edge with given RightNode and LeftNode.
Parameters
_left - Left node of this edge.
_right - Right node of this edge.
Example Use: Construct edge
Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(src, target1);
Definition at line 112 of file edge.h.
                                                                                                         {
    this->_left = _left;
    this->_right = _right;
    this->_weight = 0;
}
Member Function Documentation
AdjustEdge()
template<typename NodeStorageType >
void Markov::Edge< NodeStorageType >::AdjustEdge (long int offset)
Adjust the edge EdgeWeight with offset. Adds the offset parameter to the edge EdgeWeight.
Parameters
offset - NodeValue to be added to the EdgeWeight
Example Use: Construct edge
Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(src, target1);
e1->AdjustEdge(25);
Definition at line 119 of file edge.h.
                                                            {
    this->_weight += offset;
    this->LeftNode()->UpdateTotalVerticeWeight(offset);
}
Referenced by Markov::Model< char >::AdjustEdge(), Markov::Model< char >::Import(), Testing::MVP::MarkovModel::TEST_CLASS(), and Testing::MarkovModel::TEST_CLASS().
EdgeWeight()
template<typename NodeStorageType >
uint64_t Markov::Edge< NodeStorageType >::EdgeWeight [inline]
return edge's EdgeWeight.
Returns
edge's EdgeWeight.
Definition at line 142 of file edge.h.
                                                        {
    return this->_weight;
}
Referenced by Markov::Model< char >::Export(), and Testing::MVP::MarkovModel::TEST_CLASS().
LeftNode()
template<typename NodeStorageType >
Markov::Node< NodeStorageType > * Markov::Edge< NodeStorageType >::LeftNode
return edge's LeftNode
Returns
edge's LeftNode.
Definition at line 147 of file edge.h.
                                                                   {
    return this->_left;
}
Referenced by Markov::Model< char >::Export(), and Testing::MVP::MarkovModel::TEST_CLASS().
RightNode()
template<typename NodeStorageType >
Markov::Node< NodeStorageType > * Markov::Edge< NodeStorageType >::RightNode [inline]
return edge's RightNode
Returns
edge's RightNode.
Definition at line 152 of file edge.h.
                                                                           {
    return this->_right;
}
Referenced by Markov::Model< char >::AdjustEdge(), Markov::Model< char >::Export(), Testing::MVP::MarkovModel::TEST_CLASS(), and Markov::Node< NodeStorageType >::UpdateEdges().
SetLeftEdge()
template<typename NodeStorageType >
void Markov::Edge< NodeStorageType >::SetLeftEdge (Markov::Node< NodeStorageType > * n)
Set LeftNode of this edge.
Parameters
node - Node to be linked with.
Definition at line 132 of file edge.h.
                                                                            {
    this->_left = n;
}
Referenced by Markov::Node< NodeStorageType >::Link(), and Testing::MVP::MarkovModel::TEST_CLASS().
SetRightEdge()
template<typename NodeStorageType >
void Markov::Edge< NodeStorageType >::SetRightEdge (Markov::Node< NodeStorageType > * n)
Set RightNode of this edge.
Parameters
node - Node to be linked with.
Definition at line 137 of file edge.h.
                                                                             {
    this->_right = n;
}
Referenced by Testing::MVP::MarkovModel::TEST_CLASS().
TraverseNode()
template<typename NodeStorageType >
Markov::Node< NodeStorageType > * Markov::Edge< NodeStorageType >::TraverseNode [inline]
Traverse this edge to RightNode.
Returns
Right node. If this is a terminator node, return NULL
Example Use: Traverse a node
Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(src, target1);
e1->AdjustEdge(25);
Markov::Edge<unsigned char>* e2 = e1->traverseNode();
Definition at line 125 of file edge.h.
                                                                              {
    if (this->RightNode()->NodeValue() == 0xff) //terminator node
        return NULL;
    return _right;
}
Referenced by Testing::MVP::MarkovModel::TEST_CLASS(), and Markov::Node< NodeStorageType >::UpdateEdges().
Member Data Documentation
_left
template<typename NodeStorageType >
Node<NodeStorageType>* Markov::Edge< NodeStorageType >::_left [private]
Definition at line 95 of file edge.h.
_right
template<typename NodeStorageType >
Node<NodeStorageType>* Markov::Edge< NodeStorageType >::_right [private]
source node
Definition at line 96 of file edge.h.
_weight
template<typename NodeStorageType >
long int Markov::Edge< NodeStorageType >::_weight [private]
target node
Definition at line 97 of file edge.h.
The documentation for this class was generated from the following file:
edge.h