Markov::GUI::MarkovPasswordsGUI Class Reference
Reporting UI.
#include <MarkovPasswordsGUI.h>
Public Slots
void benchmarkSelected ()
void home ()
void pass ()
void model ()
Public Member Functions
MarkovPasswordsGUI (QWidget *parent=Q_NULLPTR)
Private Attributes
Ui::MarkovPasswordsGUIClass ui
Detailed Description
Reporting UI.
UI for reporting and debugging tools for MarkovPassword
Definition at line 19 of file MarkovPasswordsGUI.h.
Constructor & Destructor Documentation
MarkovPasswordsGUI()
Markov::GUI::MarkovPasswordsGUI::MarkovPasswordsGUI (QWidget * parent = Q_NULLPTR)
Definition at line 14 of file MarkovPasswordsGUI.cpp.
                                                               : QMainWindow(parent){
    ui.setupUi(this);
    QObject::connect(ui.pushButton, &QPushButton::clicked, this, [this] {home(); });
    QObject::connect(ui.pushButton_2, &QPushButton::clicked, this, [this] {model(); });
    QObject::connect(ui.pushButton_3, &QPushButton::clicked, this, [this] {pass(); });
}
References ui.
Member Function Documentation
benchmarkSelected
void Markov::GUI::MarkovPasswordsGUI::benchmarkSelected () [slot]
home
void MarkovPasswordsGUI::home () [slot]
Definition at line 24 of file MarkovPasswordsGUI.cpp.
                              {
    CLI* w = new CLI;
    w->show();
    this->close();
}
model
void MarkovPasswordsGUI::model () [slot]
Definition at line 42 of file MarkovPasswordsGUI.cpp.
                               {
    QWebEngineView* webkit = ui.centralWidget->findChild<QWebEngineView*>("chartArea");
    //get working directory
    char path[255];
    GetCurrentDirectoryA(255, path);
    //get absolute path to the layout html
    std::string layout = "file:///" + std::string(path) + "\\views\\index.html";
    std::replace(layout.begin(), layout.end(), '\\', '/');
    webkit->setUrl(QUrl(layout.c_str()));
}
Referenced by Python.CudaMarkopy.CudaModelMatrixCLI::_generate(), Python.Markopy.BaseCLI::_generate(), Python.Markopy.ModelMatrixCLI::_generate(), Python.Markopy.MarkovPasswordsCLI::_generate(), Python.Markopy.BaseCLI::export(), Python.Markopy.BaseCLI::import_model(), and Python.Markopy.BaseCLI::train().
pass
void MarkovPasswordsGUI::pass () [slot]
Definition at line 29 of file MarkovPasswordsGUI.cpp.
                              {
    QWebEngineView* webkit = ui.centralWidget->findChild<QWebEngineView*>("chartArea");
    //get working directory
    char path[255];
    GetCurrentDirectoryA(255, path);
    //get absolute path to the layout html
    std::string layout = "file:///" + std::string(path) + "\\views\\bar.html";
    std::replace(layout.begin(), layout.end(), '\\', '/');
    webkit->setUrl(QUrl(layout.c_str()));
}
Member Data Documentation
ui
Ui::MarkovPasswordsGUIClass Markov::GUI::MarkovPasswordsGUI::ui [private]
Definition at line 25 of file MarkovPasswordsGUI.h.
Referenced by MarkovPasswordsGUI().
The documentation for this class was generated from the following files:
Markopy/MarkovPasswordsGUI/src/MarkovPasswordsGUI.h
Markopy/MarkovPasswordsGUI/src/MarkovPasswordsGUI.cpp