Markov::API::CUDA::Random::Marsaglia Class Reference
Extension of Markov::Random::Marsaglia which is capable o working on device space.
#include <cudarandom.h>
Public Member Functions
unsigned long random ()
Generate Random Number.
Static Public Member Functions
static unsigned long * MigrateToVRAM (Markov::API::CUDA::Random::Marsaglia *MEarr, long int gridSize)
Migrate a Marsaglia[] to VRAM as seedChunk.
static __host__ void ListCudaDevices ()
List CUDA devices in the system.
Public Attributes
unsigned long x
unsigned long y
unsigned long z
Protected Member Functions
std::random_device & rd ()
Default random device for seeding.
std::default_random_engine & generator ()
Default random engine for seeding.
std::uniform_int_distribution< long long unsigned > & distribution ()
Distribution schema for seeding.
Static Protected Member Functions
static __host__ int CudaCheckNotifyErr (cudaError_t _status, const char *msg, bool bExit=true)
Check results of the last operation on GPU.
template<typename T >
static __host__ cudaError_t CudaMalloc2DToFlat (T **dst, int row, int col)
Malloc a 2D array in device space.
template<typename T >
static __host__ cudaError_t CudaMemcpy2DToFlat (T *dst, T **src, int row, int col)
Memcpy a 2D array in device space after flattening.
template<typename T >
static __host__ cudaError_t CudaMigrate2DFlat (T **dst, T **src, int row, int col)
Both malloc and memcpy a 2D array into device VRAM.
Detailed Description
Extension of Markov::Random::Marsaglia which is capable o working on device space.
Implementation of Marsaglia Random Engine. This is an implementation of Marsaglia Random engine, which for most use cases is a better fit than other solutions. Very simple mathematical formula to generate pseudorandom integer, so its crazy fast.
This implementation of the Marsaglia Engine is seeded by random.h default random engine. RandomEngine is only seeded once so its not a performance issue.
Example Use: Using Marsaglia Engine with RandomWalk
Markov::Model<char> model;
Model.import("model.mdl");
char* res = new char[11];
Markov::Random::Marsaglia MarsagliaRandomEngine;
for (int i = 0; i < 10; i++) {
    this->RandomWalk(&MarsagliaRandomEngine, 5, 10, res);
    std::cout << res << "\n";
 }
Example Use: Generating a random number with Marsaglia Engine
Markov::Random::Marsaglia me;
std::cout << me.random();
Definition at line 20 of file cudarandom.h.
Member Function Documentation
CudaCheckNotifyErr()
__host__ int Markov::API::CUDA::CUDADeviceController::CudaCheckNotifyErr (cudaError_t _status, const char * msg, bool bExit = true) [static], [protected], [inherited]
Check results of the last operation on GPU.
Check the status returned from cudaMalloc/cudaMemcpy to find failures.
If a failure occurs, its assumed beyond redemption, and exited.
Parameters
_status Cuda error status to check
msg Message to print in case of a failure
Returns
0 if successful, 1 if failure. Example output:
char *da, a = "test";
cudastatus = cudaMalloc((char **)&da, 5*sizeof(char*));
CudaCheckNotifyErr(cudastatus, "Failed to allocate VRAM for *da.\n");
Definition at line 32 of file cudaDeviceController.cu.
                                                                                                                       {
        if (_status != cudaSuccess) {
            std::cerr << "\033[1;31m" << msg << " -> " << cudaGetErrorString(_status) << " ("<< _status << ")" << "\033[0m" << "\n";
            
            if(bExit) {
                cudaDeviceReset();
                exit(1);
            }
        }
        return 0;
    }
CudaMalloc2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMalloc2DToFlat (T ** dst, int row, int col) [inline], [static], [protected], [inherited]
Malloc a 2D array in device space.
This function will allocate enough space on VRAM for flattened 2D array.
Parameters
dst destination pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
if(cudastatus!=cudaSuccess){
    CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
}
Definition at line 75 of file cudaDeviceController.h.
                                                                                 {
            cudaError_t cudastatus = cudaMalloc((T **)dst, row*col*sizeof(T));
            CudaCheckNotifyErr(cudastatus, "cudaMalloc Failed.", false);
            return cudastatus;
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
CudaMemcpy2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMemcpy2DToFlat (T * dst, T ** src, int row, int col) [inline], [static], [protected], [inherited]
Memcpy a 2D array in device space after flattening.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
cudastatus = CudaMemcpy2DToFlat<char>(*dst,src,15,15);
CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
Definition at line 103 of file cudaDeviceController.h.
                                                                                         {
            T* tempbuf = new T[row*col];
            for(int i=0;i<row;i++){
                memcpy(&(tempbuf[row*i]), src[i], col);
            }
            return cudaMemcpy(dst, tempbuf, row*col*sizeof(T), cudaMemcpyHostToDevice);
            
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
CudaMigrate2DFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat (T ** dst, T ** src, int row, int col) [inline], [static], [protected], [inherited]
Both malloc and memcpy a 2D array into device VRAM.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMigrate2DFlat<long int>(
   &dst, this->valueMatrix, this->matrixSize, this->matrixSize);
CudaCheckNotifyErr(cudastatus, " Cuda failed to initialize value matrix row.");
Definition at line 132 of file cudaDeviceController.h.
                                                                                         {
            cudaError_t cudastatus;
            cudastatus = CudaMalloc2DToFlat<T>(dst, row, col);
            if(cudastatus!=cudaSuccess){
                CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
                return cudastatus;
            }
            cudastatus = CudaMemcpy2DToFlat<T>(*dst,src,row,col);
            CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
            return cudastatus;
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
Referenced by Markov::API::CUDA::CUDADeviceController::CudaMalloc2DToFlat(), Markov::API::CUDA::CUDADeviceController::CudaMemcpy2DToFlat(), and Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
distribution()
std::uniform_int_distribution<long long unsigned>& Markov::Random::DefaultRandomEngine::distribution () [inline], [protected], [inherited]
Distribution schema for seeding.
Definition at line 90 of file random.h.
                                                                               {
            static std::uniform_int_distribution<long long unsigned> _distribution(0, 0xffffFFFF);
            return _distribution;
        }
Referenced by Markov::Random::Marsaglia::Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
generator()
std::default_random_engine& Markov::Random::DefaultRandomEngine::generator () [inline], [protected], [inherited]
Default random engine for seeding.
Definition at line 82 of file random.h.
                                                     {
            static std::default_random_engine _generator(rd()());
            return _generator;
        }
References Markov::Random::DefaultRandomEngine::rd().
Referenced by Markov::Random::Marsaglia::Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
ListCudaDevices()
__host__ void Markov::API::CUDA::CUDADeviceController::ListCudaDevices () [static], [inherited]
List CUDA devices in the system.
This function will print details of every CUDA capable device in the system.
Example output:
Device Number: 0
Device name: GeForce RTX 2070
Memory Clock Rate (KHz): 7001000
Memory Bus Width (bits): 256
Peak Memory Bandwidth (GB/s): 448.064
Max Linear Threads: 1024
Definition at line 16 of file cudaDeviceController.cu.
                                                                     { //list cuda Capable devices on host.
        int nDevices;
        cudaGetDeviceCount(&nDevices);
        for (int i = 0; i < nDevices; i++) {
            cudaDeviceProp prop;
            cudaGetDeviceProperties(&prop, i);
            std::cerr << "Device Number: " << i << "\n";
            std::cerr << "Device name: " << prop.name << "\n";
            std::cerr << "Memory Clock Rate (KHz): " << prop.memoryClockRate << "\n";
            std::cerr << "Memory Bus Width (bits): " << prop.memoryBusWidth << "\n";
            std::cerr << "Peak Memory Bandwidth (GB/s): " << 2.0 * prop.memoryClockRate * (prop.memoryBusWidth / 8) / 1.0e6 << "\n";
            std::cerr << "Max Linear Threads: " << prop.maxThreadsDim[0] << "\n";
            
        }
    }
MigrateToVRAM()
static unsigned long* Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM (Markov::API::CUDA::Random::Marsaglia * MEarr, long int gridSize) [inline], [static]
Migrate a Marsaglia[] to VRAM as seedChunk.
Parameters
MEarr Array of Marsaglia Engines
gridSize GridSize of the CUDA Kernel, aka size of array
Returns
pointer to the resulting seed chunk in device VRAM.
Definition at line 28 of file cudarandom.h.
                                                                                                   {
            cudaError_t cudastatus;
            unsigned long* seedChunk;
            cudastatus = cudaMalloc((unsigned long**)&seedChunk, gridSize*3*sizeof(unsigned long));
            CudaCheckNotifyErr(cudastatus, "Failed to allocate seed buffer");
            unsigned long *temp = new unsigned long[gridSize*3];
            for(int i=0;i<gridSize;i++){
                temp[i*3] = MEarr[i].x;
                temp[i*3+1] = MEarr[i].y;
                temp[i*3+2] = MEarr[i].z;
            }
            //for(int i=0;i<gridSize*3;i++) std::cout << temp[i] << "\n";
            cudaMemcpy(seedChunk, temp, gridSize*3*sizeof(unsigned long), cudaMemcpyHostToDevice);
            CudaCheckNotifyErr(cudastatus, "Failed to memcpy seed buffer.");
            
            delete[] temp;
            return seedChunk;
        }
References Markov::Random::Marsaglia::x, Markov::Random::Marsaglia::y, and Markov::Random::Marsaglia::z.
Referenced by Markov::API::CUDA::CUDAModelMatrix::prepKernelMemoryChannel().
random()
unsigned long Markov::Random::Marsaglia::random () [inline], [virtual], [inherited]
Generate Random Number.
Returns
random number in long range.
Reimplemented from Markov::Random::DefaultRandomEngine.
Definition at line 140 of file random.h.
                                 {
        unsigned long t;
        x ^= x << 16;
        x ^= x >> 5;
        x ^= x << 1;
        t = x;
        x = y;
        y = z;
        z = t ^ x ^ y;
        return z;
    }
References Markov::Random::Marsaglia::x, Markov::Random::Marsaglia::y, and Markov::Random::Marsaglia::z.
Referenced by Markov::API::ModelMatrix::FastRandomWalkThread().
rd()
std::random_device& Markov::Random::DefaultRandomEngine::rd () [inline], [protected], [inherited]
Default random device for seeding.
Definition at line 74 of file random.h.
                                      {
            static std::random_device _rd;
            return _rd;
        }
Referenced by Markov::Random::DefaultRandomEngine::generator().
Member Data Documentation
x
unsigned long Markov::Random::Marsaglia::x [inherited]
Definition at line 155 of file random.h.
Referenced by Markov::Random::Marsaglia::Marsaglia(), MigrateToVRAM(), and Markov::Random::Marsaglia::random().
y
unsigned long Markov::Random::Marsaglia::y [inherited]
Definition at line 156 of file random.h.
Referenced by Markov::Random::Marsaglia::Marsaglia(), MigrateToVRAM(), and Markov::Random::Marsaglia::random().
z
unsigned long Markov::Random::Marsaglia::z [inherited]
Definition at line 157 of file random.h.
Referenced by Markov::Random::Marsaglia::Marsaglia(), MigrateToVRAM(), and Markov::Random::Marsaglia::random().
The documentation for this class was generated from the following file:
cudarandom.h