Markov::Random::Mersenne Class Reference
Implementation of Mersenne Twister Engine.
#include <random.h>
Public Member Functions
unsigned long random ()
Generate Random Number.
Protected Member Functions
std::random_device & rd ()
Default random device for seeding.
std::default_random_engine & generator ()
Default random engine for seeding.
std::uniform_int_distribution< long long unsigned > & distribution ()
Distribution schema for seeding.
Detailed Description
Implementation of Mersenne Twister Engine.
This is an implementation of Mersenne Twister Engine, which is slow but is a good implementation for high entropy pseudorandom.
Example Use: Using Mersenne Engine with RandomWalk
Markov::Model<char> model;
Model.import("model.mdl");
char* res = new char[11];
Markov::Random::Mersenne MersenneTwisterEngine;
for (int i = 0; i < 10; i++) {
    this->RandomWalk(&MersenneTwisterEngine, 5, 10, res);
    std::cout << res << "\n";
 }
Example Use: Generating a random number with Marsaglia Engine
Markov::Random::Mersenne me;
std::cout << me.random();
Definition at line 185 of file random.h.
Member Function Documentation
distribution()
std::uniform_int_distribution<long long unsigned>& Markov::Random::DefaultRandomEngine::distribution () [inline], [protected], [inherited]
Distribution schema for seeding.
Definition at line 90 of file random.h.
                                                                               {
            static std::uniform_int_distribution<long long unsigned> _distribution(0, 0xffffFFFF);
            return _distribution;
        }
Referenced by Markov::Random::Marsaglia::Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
generator()
std::default_random_engine& Markov::Random::DefaultRandomEngine::generator () [inline], [protected], [inherited]
Default random engine for seeding.
Definition at line 82 of file random.h.
                                                     {
            static std::default_random_engine _generator(rd()());
            return _generator;
        }
References Markov::Random::DefaultRandomEngine::rd().
Referenced by Markov::Random::Marsaglia::Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
random()
unsigned long Markov::Random::DefaultRandomEngine::random () [inline], [virtual], [inherited]
Generate Random Number.
Returns
random number in long range.
Implements Markov::Random::RandomEngine.
Reimplemented in Markov::Random::Marsaglia.
Definition at line 66 of file random.h.
                                     {
            return this->distribution()(this->generator());
        }
References Markov::Random::DefaultRandomEngine::distribution(), and Markov::Random::DefaultRandomEngine::generator().
rd()
std::random_device& Markov::Random::DefaultRandomEngine::rd () [inline], [protected], [inherited]
Default random device for seeding.
Definition at line 74 of file random.h.
                                      {
            static std::random_device _rd;
            return _rd;
        }
Referenced by Markov::Random::DefaultRandomEngine::generator().
The documentation for this class was generated from the following file:
Markopy/MarkovModel/src/random.h