Markov::API::CUDA::CUDAModelMatrix Class Reference
Extension of Markov::API::ModelMatrix which is modified to run on GPU devices.
#include <cudaModelMatrix.h>
Public Member Functions
__host__ void MigrateMatrix ()
Migrate the class members to the VRAM.
__host__ void FlattenMatrix ()
Flatten migrated matrix from 2d to 1d.
__host__ void FastRandomWalk (unsigned long int n, const char *wordlistFileName, int minLen, int maxLen, bool bFileIO, bool bInfinite)
Random walk on the Matrix-reduced Markov::Model.
bool ConstructMatrix ()
Construct the related Matrix data for the model.
void DumpJSON ()
Debug function to dump the model to a JSON file.
int FastRandomWalk (unsigned long int n, const char *wordlistFileName, int minLen=6, int maxLen=12, int threads=20, bool bFileIO=true)
Random walk on the Matrix-reduced Markov::Model.
void Import (const char *filename)
Open a file to import with filename, and call bool Model::Import with std::ifstream.
bool Import (std::ifstream *)
Import a file to construct the model.
void Train (const char *datasetFileName, char delimiter, int threads)
Train the model with the dataset file.
std::ifstream * OpenDatasetFile (const char *filename)
Open dataset file and return the ifstream pointer.
std::ofstream * Save (const char *filename)
Export model to file.
void Generate (unsigned long int n, const char *wordlistFileName, int minLen=6, int maxLen=12, int threads=20)
Call Markov::Model::RandomWalk n times, and collect output.
void Buff (const char *str, double multiplier, bool bDontAdjustSelfLoops=true, bool bDontAdjustExtendedLoops=false)
Buff expression of some characters in the model.
char * RandomWalk (Markov::Random::RandomEngine *randomEngine, int minSetting, int maxSetting, char *buffer)
Do a random walk on this model.
void AdjustEdge (const char *payload, long int occurrence)
Adjust the model with a single string.
bool Export (std::ofstream *)
Export a file of the model.
bool Export (const char *filename)
Open a file to export with filename, and call bool Model::Export with std::ofstream.
Node< char > * StarterNode ()
Return starter Node.
std::vector< Edge< char > * > * Edges ()
Return a vector of all the edges in the model.
std::map< char, Node< char > * > * Nodes ()
Return starter Node.
void OptimizeEdgeOrder ()
Sort edges of all nodes in the model ordered by edge weights.
Static Public Member Functions
static __host__ void ListCudaDevices ()
List CUDA devices in the system.
Protected Member Functions
__host__ char * AllocVRAMOutputBuffer (long int n, long int singleGenMaxLen, long int CUDAKernelGridSize, long int sizePerGrid)
Allocate the output buffer for kernel operation.
__host__ void LaunchAsyncKernel (int kernelID, int minLen, int maxLen)
__host__ void prepKernelMemoryChannel (int numberOfStreams)
__host__ void GatherAsyncKernelOutput (int kernelID, bool bFileIO, std::ofstream &wordlist)
int FastRandomWalk (unsigned long int n, std::ofstream *wordlist, int minLen=6, int maxLen=12, int threads=20, bool bFileIO=true)
Random walk on the Matrix-reduced Markov::Model.
void FastRandomWalkPartition (std::mutex *mlock, std::ofstream *wordlist, unsigned long int n, int minLen, int maxLen, bool bFileIO, int threads)
A single partition of FastRandomWalk event.
void FastRandomWalkThread (std::mutex *mlock, std::ofstream *wordlist, unsigned long int n, int minLen, int maxLen, int id, bool bFileIO)
A single thread of a single partition of FastRandomWalk.
bool DeallocateMatrix ()
Deallocate matrix and make it ready for re-construction.
Static Protected Member Functions
static __host__ int CudaCheckNotifyErr (cudaError_t _status, const char *msg, bool bExit=true)
Check results of the last operation on GPU.
template<typename T >
static __host__ cudaError_t CudaMalloc2DToFlat (T **dst, int row, int col)
Malloc a 2D array in device space.
template<typename T >
static __host__ cudaError_t CudaMemcpy2DToFlat (T *dst, T **src, int row, int col)
Memcpy a 2D array in device space after flattening.
template<typename T >
static __host__ cudaError_t CudaMigrate2DFlat (T **dst, T **src, int row, int col)
Both malloc and memcpy a 2D array into device VRAM.
Protected Attributes
char ** edgeMatrix
2-D Character array for the edge Matrix (The characters of Nodes)
long int ** valueMatrix
2-d Integer array for the value Matrix (For the weights of Edges)
int matrixSize
to hold Matrix size
char * matrixIndex
to hold the Matrix index (To hold the orders of 2-D arrays')
long int * totalEdgeWeights
Array of the Total Edge Weights.
bool ready
True when matrix is constructed. False if not.
Private Member Functions
void TrainThread (Markov::API::Concurrency::ThreadSharedListHandler *listhandler, char delimiter)
A single thread invoked by the Train function.
void GenerateThread (std::mutex *outputLock, unsigned long int n, std::ofstream *wordlist, int minLen, int maxLen)
A single thread invoked by the Generate function.
Private Attributes
char * device_edgeMatrix
VRAM Address pointer of edge matrix (from modelMatrix.h)
long int * device_valueMatrix
VRAM Address pointer of value matrix (from modelMatrix.h)
char * device_matrixIndex
VRAM Address pointer of matrixIndex (from modelMatrix.h)
long int * device_totalEdgeWeights
VRAM Address pointer of total edge weights (from modelMatrix.h)
char ** device_outputBuffer
RandomWalk results in device.
char ** outputBuffer
RandomWalk results in host.
char * flatEdgeMatrix
Adding Edge matrix end-to-end and resize to 1-D array for better perfomance on traversing.
long int * flatValueMatrix
Adding Value matrix end-to-end and resize to 1-D array for better perfomance on traversing.
int cudaBlocks
int cudaThreads
int iterationsPerKernelThread
long int totalOutputPerSync
long int totalOutputPerKernel
int numberOfPartitions
int cudaGridSize
int cudaMemPerGrid
long int cudaPerKernelAllocationSize
int alternatingKernels
unsigned long ** device_seeds
cudaStream_t * cudastreams
std::ifstream * datasetFile
std::ofstream * modelSavefile
Dataset file input of our system
std::ofstream * outputFile
File to save model of our system
std::map< char, Node< char > * > nodes
Map LeftNode is the Nodes NodeValue Map RightNode is the node pointer.
Node< char > * starterNode
Starter Node of this model.
std::vector< Edge< char > * > edges
A list of all edges in this model.
Detailed Description
Extension of Markov::API::ModelMatrix which is modified to run on GPU devices.
This implementation only supports Nvidia devices.
Class to flatten and reduce Markov::Model to a Matrix. Matrix level operations can be used for Generation events, with a significant performance optimization at the cost of O(N) memory complexity (O(1) memory space for slow mode)
To limit the maximum memory usage, each generation operation is partitioned into 50M chunks for allocation. Threads are sychronized and files are flushed every 50M operations.
Definition at line 19 of file cudaModelMatrix.h.
Member Function Documentation
AdjustEdge()
void Markov::Model< char >::AdjustEdge (const NodeStorageType * payload, long int occurrence) [inherited]
Adjust the model with a single string.
Start from the starter node, and for each character, AdjustEdge the edge EdgeWeight from current node to the next, until NULL character is reached.
Then, update the edge EdgeWeight from current node, to the terminator node.
This function is used for training purposes, as it can be used for adjusting the model with each line of the corpus file.
Example Use: Create an empty model and train it with string: `testdata`
Markov::Model<char> model;
char test[] = "testdata";
model.AdjustEdge(test, 15);
Parameters
string - String that is passed from the training, and will be used to AdjustEdge the model with
occurrence - Occurrence of this string.
Definition at line 337 of file model.h.
                                                                                                 {
    NodeStorageType p = payload[0];
    Markov::Node<NodeStorageType>* curnode = this->starterNode;
    Markov::Edge<NodeStorageType>* e;
    int i = 0;
    if (p == 0) return;
    while (p != 0) {
        e = curnode->FindEdge(p);
        if (e == NULL) return;
        e->AdjustEdge(occurrence);
        curnode = e->RightNode();
        p = payload[++i];
    }
    e = curnode->FindEdge('\xff');
    e->AdjustEdge(occurrence);
    return;
}
AllocVRAMOutputBuffer()
__host__ char* Markov::API::CUDA::CUDAModelMatrix::AllocVRAMOutputBuffer (long int n, long int singleGenMaxLen, long int CUDAKernelGridSize, long int sizePerGrid) [protected]
Allocate the output buffer for kernel operation.
TODO
Parameters
n - Number of passwords to generate.
singleGenMaxLen - maximum string length for a single generation
CUDAKernelGridSize - Total number of grid members in CUDA kernel
sizePerGrid - Size to allocate per grid member
Returns
pointer to the allocation on VRAM
Buff()
void Markov::API::MarkovPasswords::Buff (const char * str, double multiplier, bool bDontAdjustSelfLoops = true, bool bDontAdjustExtendedLoops = false) [inherited]
Buff expression of some characters in the model.
Parameters
str A string containing all the characters to be buffed
multiplier A constant value to buff the nodes with.
bDontAdjustSelfEdges Do not adjust weights if target node is same as source node
bDontAdjustExtendedLoops Do not adjust if both source and target nodes are in first parameter
Definition at line 153 of file markovPasswords.cpp.
                                                                                                                               {
    std::string buffstr(str);
    std::map< char, Node< char > * > *nodes;
    std::map< char, Edge< char > * > *edges;
    nodes = this->Nodes();
    int i=0;
    for (auto const& [repr, node] : *nodes){
        edges = node->Edges();
        for (auto const& [targetrepr, edge] : *edges){
            if(buffstr.find(targetrepr)!= std::string::npos){
                if(bDontAdjustSelfLoops && repr==targetrepr) continue;
                if(bDontAdjustExtendedLoops){
                    if(buffstr.find(repr)!= std::string::npos){
                        continue;
                    }
                }
                long int weight = edge->EdgeWeight();
                weight = weight*multiplier;
                edge->AdjustEdge(weight);
            }
        }
        i++;
    }
    this->OptimizeEdgeOrder();
}
References Markov::Edge< NodeStorageType >::AdjustEdge(), Markov::Node< storageType >::Edges(), Markov::Edge< NodeStorageType >::EdgeWeight(), Markov::Model< NodeStorageType >::Nodes(), and Markov::Model< NodeStorageType >::OptimizeEdgeOrder().
Referenced by main().
ConstructMatrix()
bool Markov::API::ModelMatrix::ConstructMatrix () [inherited]
Construct the related Matrix data for the model.
This operation can be used after importing/training to allocate and populate the matrix content.
this will initialize: char** edgeMatrix -> a 2D array of mapping left and right connections of each edge. long int **valueMatrix -> a 2D array representing the edge weights. int matrixSize -> Size of the matrix, aka total number of nodes. char* matrixIndex -> order of nodes in the model long int *totalEdgeWeights -> total edge weights of each Node.
Returns
True if constructed. False if already construced.
Definition at line 31 of file modelMatrix.cpp.
                                          {
    if(this->ready) return false;
    this->matrixSize = this->StarterNode()->edgesV.size() + 2;
    this->matrixIndex = new char[this->matrixSize];
    this->totalEdgeWeights = new long int[this->matrixSize];
    this->edgeMatrix = new char*[this->matrixSize];
    for(int i=0;i<this->matrixSize;i++){
        this->edgeMatrix[i] = new char[this->matrixSize];
    }
    this->valueMatrix = new long int*[this->matrixSize];
    for(int i=0;i<this->matrixSize;i++){
        this->valueMatrix[i] = new long int[this->matrixSize];
    }
    std::map< char, Node< char > * > *nodes;
    nodes = this->Nodes();
    int i=0;
    for (auto const& [repr, node] : *nodes){
        if(repr!=0) this->matrixIndex[i] = repr;
        else this->matrixIndex[i] = 199;
        this->totalEdgeWeights[i] = node->TotalEdgeWeights();
        for(int j=0;j<this->matrixSize;j++){
            char val = node->NodeValue();
            if(val < 0){
                for(int k=0;k<this->matrixSize;k++){
                    this->valueMatrix[i][k] = 0;
                    this->edgeMatrix[i][k] = 255;
                }
                break;
            }
            else if(node->NodeValue() == 0 && j>(this->matrixSize-3)){
                this->valueMatrix[i][j] = 0;
                this->edgeMatrix[i][j] = 255;
            }else if(j==(this->matrixSize-1)) {
                this->valueMatrix[i][j] = 0;
                this->edgeMatrix[i][j] = 255;
            }else{
                this->valueMatrix[i][j] = node->edgesV[j]->EdgeWeight();
                this->edgeMatrix[i][j] = node->edgesV[j]->RightNode()->NodeValue();
            }
        }
        i++;
    }
    this->ready = true;
    return true;
    //this->DumpJSON();
}
References Markov::API::ModelMatrix::edgeMatrix, Markov::Edge< NodeStorageType >::EdgeWeight(), Markov::API::ModelMatrix::matrixIndex, Markov::API::ModelMatrix::matrixSize, Markov::Model< NodeStorageType >::Nodes(), Markov::Node< storageType >::NodeValue(), Markov::API::ModelMatrix::ready, Markov::Edge< NodeStorageType >::RightNode(), Markov::Model< NodeStorageType >::StarterNode(), Markov::Node< storageType >::TotalEdgeWeights(), Markov::API::ModelMatrix::totalEdgeWeights, and Markov::API::ModelMatrix::valueMatrix.
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE(), Markov::API::ModelMatrix::Import(), and Markov::API::ModelMatrix::Train().
CudaCheckNotifyErr()
__host__ int Markov::API::CUDA::CUDADeviceController::CudaCheckNotifyErr (cudaError_t _status, const char * msg, bool bExit = true) [static], [protected], [inherited]
Check results of the last operation on GPU.
Check the status returned from cudaMalloc/cudaMemcpy to find failures.
If a failure occurs, its assumed beyond redemption, and exited.
Parameters
_status Cuda error status to check
msg Message to print in case of a failure
Returns
0 if successful, 1 if failure. Example output:
char *da, a = "test";
cudastatus = cudaMalloc((char **)&da, 5*sizeof(char*));
CudaCheckNotifyErr(cudastatus, "Failed to allocate VRAM for *da.\n");
Definition at line 32 of file cudaDeviceController.cu.
                                                                                                                       {
        if (_status != cudaSuccess) {
            std::cerr << "\033[1;31m" << msg << " -> " << cudaGetErrorString(_status) << " ("<< _status << ")" << "\033[0m" << "\n";
            
            if(bExit) {
                cudaDeviceReset();
                exit(1);
            }
        }
        return 0;
    }
CudaMalloc2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMalloc2DToFlat (T ** dst, int row, int col) [inline], [static], [protected], [inherited]
Malloc a 2D array in device space.
This function will allocate enough space on VRAM for flattened 2D array.
Parameters
dst destination pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
if(cudastatus!=cudaSuccess){
    CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
}
Definition at line 75 of file cudaDeviceController.h.
                                                                                 {
            cudaError_t cudastatus = cudaMalloc((T **)dst, row*col*sizeof(T));
            CudaCheckNotifyErr(cudastatus, "cudaMalloc Failed.", false);
            return cudastatus;
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
CudaMemcpy2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMemcpy2DToFlat (T * dst, T ** src, int row, int col) [inline], [static], [protected], [inherited]
Memcpy a 2D array in device space after flattening.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
cudastatus = CudaMemcpy2DToFlat<char>(*dst,src,15,15);
CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
Definition at line 103 of file cudaDeviceController.h.
                                                                                         {
            T* tempbuf = new T[row*col];
            for(int i=0;i<row;i++){
                memcpy(&(tempbuf[row*i]), src[i], col);
            }
            return cudaMemcpy(dst, tempbuf, row*col*sizeof(T), cudaMemcpyHostToDevice);
            
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
CudaMigrate2DFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat (T ** dst, T ** src, int row, int col) [inline], [static], [protected], [inherited]
Both malloc and memcpy a 2D array into device VRAM.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMigrate2DFlat<long int>(
   &dst, this->valueMatrix, this->matrixSize, this->matrixSize);
CudaCheckNotifyErr(cudastatus, " Cuda failed to initialize value matrix row.");
Definition at line 132 of file cudaDeviceController.h.
                                                                                         {
            cudaError_t cudastatus;
            cudastatus = CudaMalloc2DToFlat<T>(dst, row, col);
            if(cudastatus!=cudaSuccess){
                CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
                return cudastatus;
            }
            cudastatus = CudaMemcpy2DToFlat<T>(*dst,src,row,col);
            CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
            return cudastatus;
        }
References Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
Referenced by Markov::API::CUDA::CUDADeviceController::CudaMalloc2DToFlat(), Markov::API::CUDA::CUDADeviceController::CudaMemcpy2DToFlat(), and Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat().
DeallocateMatrix()
bool Markov::API::ModelMatrix::DeallocateMatrix () [protected], [inherited]
Deallocate matrix and make it ready for re-construction.
Returns
True if deallocated. False if matrix was not initialized
Definition at line 81 of file modelMatrix.cpp.
                                           {
    if(!this->ready) return false;
    delete[] this->matrixIndex;
    delete[] this->totalEdgeWeights;
    for(int i=0;i<this->matrixSize;i++){
        delete[] this->edgeMatrix[i];
    }
    delete[] this->edgeMatrix;
    for(int i=0;i<this->matrixSize;i++){
        delete[] this->valueMatrix[i];
    }
    delete[] this->valueMatrix;
    this->matrixSize = -1;
    this->ready = false;
    return true;
}
References Markov::API::ModelMatrix::edgeMatrix, Markov::API::ModelMatrix::matrixIndex, Markov::API::ModelMatrix::matrixSize, Markov::API::ModelMatrix::ready, Markov::API::ModelMatrix::totalEdgeWeights, and Markov::API::ModelMatrix::valueMatrix.
Referenced by Markov::API::ModelMatrix::Import(), and Markov::API::ModelMatrix::Train().
DumpJSON()
void Markov::API::ModelMatrix::DumpJSON () [inherited]
Debug function to dump the model to a JSON file.
Might not work 100%. Not meant for production use.
Definition at line 101 of file modelMatrix.cpp.
                                   {
    std::cout << "{\n \"index\": \"";
    for(int i=0;i<this->matrixSize;i++){
        if(this->matrixIndex[i]=='"') std::cout << "\\\"";
        else if(this->matrixIndex[i]=='\\') std::cout << "\\\\";
        else if(this->matrixIndex[i]==0) std::cout << "\\\\x00";
        else if(i==0) std::cout << "\\\\xff";
        else if(this->matrixIndex[i]=='\n') std::cout << "\\n";
        else std::cout << this->matrixIndex[i];
    }
    std::cout <<
    "\",\n"
    " \"edgemap\": {\n";
    for(int i=0;i<this->matrixSize;i++){
        if(this->matrixIndex[i]=='"') std::cout << " \"\\\"\": [";
        else if(this->matrixIndex[i]=='\\') std::cout << " \"\\\\\": [";
        else if(this->matrixIndex[i]==0) std::cout << " \"\\\\x00\": [";
        else if(this->matrixIndex[i]<0) std::cout << " \"\\\\xff\": [";
        else std::cout << " \"" << this->matrixIndex[i] << "\": [";
        for(int j=0;j<this->matrixSize;j++){
            if(this->edgeMatrix[i][j]=='"') std::cout << "\"\\\"\"";
            else if(this->edgeMatrix[i][j]=='\\') std::cout << "\"\\\\\"";
            else if(this->edgeMatrix[i][j]==0) std::cout << "\"\\\\x00\"";
            else if(this->edgeMatrix[i][j]<0) std::cout << "\"\\\\xff\"";
            else if(this->matrixIndex[i]=='\n') std::cout << "\"\\n\"";
            else std::cout << "\"" << this->edgeMatrix[i][j] << "\"";
            if(j!=this->matrixSize-1) std::cout << ", ";
        }
        std::cout << "],\n";
    }
    std::cout << "},\n";
    std::cout << "\" weightmap\": {\n";
    for(int i=0;i<this->matrixSize;i++){
        if(this->matrixIndex[i]=='"') std::cout << " \"\\\"\": [";
        else if(this->matrixIndex[i]=='\\') std::cout << " \"\\\\\": [";
        else if(this->matrixIndex[i]==0) std::cout << " \"\\\\x00\": [";
        else if(this->matrixIndex[i]<0) std::cout << " \"\\\\xff\": [";
        else std::cout << " \"" << this->matrixIndex[i] << "\": [";
        for(int j=0;j<this->matrixSize;j++){
            std::cout << this->valueMatrix[i][j];
            if(j!=this->matrixSize-1) std::cout << ", ";
        }
        std::cout << "],\n";
    }
    std::cout << " }\n}\n";
}
References Markov::API::ModelMatrix::edgeMatrix, Markov::API::ModelMatrix::matrixIndex, Markov::API::ModelMatrix::matrixSize, and Markov::API::ModelMatrix::valueMatrix.
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE().
Edges()
std::vector<Edge<char >*>* Markov::Model< char >::Edges () [inline], [inherited]
Return a vector of all the edges in the model.
Returns
vector of edges
Definition at line 176 of file model.h.
{ return &edges;}
Export() [1/2]
bool Markov::Model< char >::Export (const char * filename) [inherited]
Open a file to export with filename, and call bool Model::Export with std::ofstream.
Returns
True if successful, False for incomplete models or corrupt file formats
Example Use: Export file to filename
Markov::Model<char> model;
model.Export("test.mdl");
Definition at line 300 of file model.h.
                                                              {
    std::ofstream exportfile;
    exportfile.open(filename);
    return this->Export(&exportfile);
}
Export() [2/2]
bool Markov::Model< char >::Export (std::ofstream * f) [inherited]
Export a file of the model.
File contains a list of edges. Format is: Left_repr;EdgeWeight;right_repr. For more information on the format, check out the project wiki or github readme.
Iterate over this vertices, and their edges, and write them to file.
Returns
True if successful, False for incomplete models.
Example Use: Export file to ofstream
Markov::Model<char> model;
std::ofstream file("test.mdl");
model.Export(&file);
Definition at line 288 of file model.h.
                                                        {
    Markov::Edge<NodeStorageType>* e;
    for (std::vector<int>::size_type i = 0; i != this->edges.size(); i++) {
        e = this->edges[i];
        //std::cout << e->LeftNode()->NodeValue() << "," << e->EdgeWeight() << "," << e->RightNode()->NodeValue() << "\n";
        *f << e->LeftNode()->NodeValue() << "," << e->EdgeWeight() << "," << e->RightNode()->NodeValue() << "\n";
    }
    return true;
}
FastRandomWalk() [1/3]
__host__ void Markov::API::CUDA::CUDAModelMatrix::FastRandomWalk (unsigned long int n, const char * wordlistFileName, int minLen, int maxLen, bool bFileIO, bool bInfinite)
Random walk on the Matrix-reduced Markov::Model.
TODO
Parameters
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
threads - number of OS threads to spawn
bFileIO - If false, filename will be ignored and will output to stdout.
Markov::API::ModelMatrix mp;
mp.Import("models/finished.mdl");
mp.FastRandomWalk(50000000,"./wordlist.txt",6,12,25, true);
Definition at line 58 of file cudaModelMatrix.cu.
                                                                                                                                                                     {
        cudaDeviceProp prop;
        int device=0;
        cudaGetDeviceProperties(&prop, device);
        cudaChooseDevice(&device, &prop);
        //std::cout << "Flattening matrix." << std::endl;
        this->FlattenMatrix();
        //std::cout << "Migrating matrix." << std::endl;
        this->MigrateMatrix();
        //std::cout << "Migrated matrix." << std::endl;
        std::ofstream wordlist;
        if(bFileIO)
            wordlist.open(wordlistFileName);
        cudaBlocks = 1024;
        cudaThreads = 256;
        iterationsPerKernelThread = 100;
        alternatingKernels = 2;
        totalOutputPerKernel = (long int)cudaBlocks*(long int)cudaThreads*iterationsPerKernelThread;
        totalOutputPerSync= totalOutputPerKernel*alternatingKernels;
        numberOfPartitions = n/totalOutputPerSync;
        cudaGridSize = cudaBlocks*cudaThreads;
        cudaMemPerGrid = (maxLen+2)*iterationsPerKernelThread;
        cudaPerKernelAllocationSize = cudaGridSize*cudaMemPerGrid;
        this->prepKernelMemoryChannel(alternatingKernels);
        
        unsigned long int leftover = n - (totalOutputPerSync*numberOfPartitions);
        if(bInfinite && !numberOfPartitions) numberOfPartitions=5;
        std::cerr << cudaPerKernelAllocationSize << "\n";
        if(n%totalOutputPerSync) std::cerr << "For optimization, request outputs muliples of "<< totalOutputPerSync << ".\n";
        //start kernelID 1
        this->LaunchAsyncKernel(1, minLen, maxLen);
        for(int i=1;i<numberOfPartitions;i++){
            if(bInfinite) i=0;
            //wait kernelID1 to finish, and start kernelID 0
            cudaStreamSynchronize(this->cudastreams[1]);
            this->LaunchAsyncKernel(0, minLen, maxLen);
            //start memcpy from kernel 1 (block until done)
            this->GatherAsyncKernelOutput(1, bFileIO, wordlist);
            
            //wait kernelID 0 to finish, then start kernelID1
            cudaStreamSynchronize(this->cudastreams[0]);
            this->LaunchAsyncKernel(1, minLen, maxLen);
            //start memcpy from kernel 0 (block until done)
            this->GatherAsyncKernelOutput(0, bFileIO, wordlist);
            
        }
        //wait kernelID1 to finish, and start kernelID 0
        cudaStreamSynchronize(this->cudastreams[1]);
        this->LaunchAsyncKernel(0, minLen, maxLen);
        this->GatherAsyncKernelOutput(1, bFileIO, wordlist);
        cudaStreamSynchronize(this->cudastreams[0]);
        this->GatherAsyncKernelOutput(0, bFileIO, wordlist);
        
        if(!leftover) return;
        alternatingKernels=1;
        std::cerr << "Remaining line count (" << leftover << ") is lower than partition. Adjusting CUDA workload..\n";
        this->iterationsPerKernelThread = leftover/cudaGridSize;
        this->LaunchAsyncKernel(0, minLen, maxLen);
        cudaStreamSynchronize(this->cudastreams[0]);
        this->GatherAsyncKernelOutput(0, bFileIO, wordlist);
        
        leftover -= this->iterationsPerKernelThread*cudaGridSize;
        if(!leftover) return;
        std::cerr << "Remaining line count (" << leftover << ") is lower than minimum possible. Handing over to CPU generation.\n";
        this->iterationsPerKernelThread = leftover/cudaGridSize;
        leftover -= this->iterationsPerKernelThread;
        if(!leftover) return;
        std::cerr << "Remaining " << leftover << " lines are absolutely not worth printing.\n";
        Markov::API::ModelMatrix::ConstructMatrix();
        Markov::API::ModelMatrix::FastRandomWalk(leftover, &wordlist, minLen, maxLen, 1, bFileIO);
    }
References alternatingKernels, cudaBlocks, cudaGridSize, cudaMemPerGrid, cudaPerKernelAllocationSize, cudaThreads, iterationsPerKernelThread, numberOfPartitions, totalOutputPerKernel, and totalOutputPerSync.
FastRandomWalk() [2/3]
int Markov::API::ModelMatrix::FastRandomWalk (unsigned long int n, const char * wordlistFileName, int minLen = 6, int maxLen = 12, int threads = 20, bool bFileIO = true) [inherited]
Random walk on the Matrix-reduced Markov::Model.
This has an O(N) Memory complexity. To limit the maximum usage, requests with n>50M are partitioned using Markov::API::ModelMatrix::FastRandomWalkPartition.
If n>50M, threads are going to be synced, files are going to be flushed, and buffers will be reallocated every 50M generations. This comes at a minor performance penalty.
While it has the same functionality, this operation reduces Markov::API::MarkovPasswords::Generate runtime by %96.5
This function has deprecated Markov::API::MarkovPasswords::Generate, and will eventually replace it.
Parameters
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
threads - number of OS threads to spawn
bFileIO - If false, filename will be ignored and will output to stdout.
Markov::API::ModelMatrix mp;
mp.Import("models/finished.mdl");
mp.FastRandomWalk(50000000,"./wordlist.txt",6,12,25, true);
Definition at line 217 of file modelMatrix.cpp.
                                                                                                                                            {
    std::ofstream wordlist;
    if(bFileIO)
        wordlist.open(wordlistFileName);
    this->FastRandomWalk(n, &wordlist, minLen, maxLen, threads, bFileIO);
    return 0;
}
References Markov::API::ModelMatrix::FastRandomWalk().
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE().
FastRandomWalk() [3/3]
int Markov::API::ModelMatrix::FastRandomWalk (unsigned long int n, std::ofstream * wordlist, int minLen = 6, int maxLen = 12, int threads = 20, bool bFileIO = true) [protected], [inherited]
Random walk on the Matrix-reduced Markov::Model.
This has an O(N) Memory complexity. To limit the maximum usage, requests with n>50M are partitioned using Markov::API::ModelMatrix::FastRandomWalkPartition.
If n>50M, threads are going to be synced, files are going to be flushed, and buffers will be reallocated every 50M generations. This comes at a minor performance penalty.
While it has the same functionality, this operation reduces Markov::API::MarkovPasswords::Generate runtime by %96.5
This function has deprecated Markov::API::MarkovPasswords::Generate, and will eventually replace it.
Parameters
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
threads - number of OS threads to spawn
bFileIO - If false, filename will be ignored and will output to stdout.
Markov::API::ModelMatrix mp;
mp.Import("models/finished.mdl");
mp.FastRandomWalk(50000000,"./wordlist.txt",6,12,25, true);
Definition at line 204 of file modelMatrix.cpp.
                                                                                                                                     {
    
    std::mutex mlock;
    if(n<=50000000ull) this->FastRandomWalkPartition(&mlock, wordlist, n, minLen, maxLen, bFileIO, threads);
    else{
        int numberOfPartitions = n/50000000ull;
        for(int i=0;i<numberOfPartitions;i++)
            this->FastRandomWalkPartition(&mlock, wordlist, 50000000ull, minLen, maxLen, bFileIO, threads);
    }
    return 0;
}
References Markov::API::ModelMatrix::FastRandomWalkPartition().
Referenced by Markov::API::ModelMatrix::FastRandomWalk().
FastRandomWalkPartition()
void Markov::API::ModelMatrix::FastRandomWalkPartition (std::mutex * mlock, std::ofstream * wordlist, unsigned long int n, int minLen, int maxLen, bool bFileIO, int threads) [protected], [inherited]
A single partition of FastRandomWalk event.
Since FastRandomWalk has to allocate its output buffer before operation starts and writes data in chunks, large n parameters would lead to huge memory allocations. Without Partitioning:
50M results 12 characters max -> 550 Mb Memory allocation
5B results 12 characters max -> 55 Gb Memory allocation
50B results 12 characters max -> 550GB Memory allocation
Instead, FastRandomWalk is partitioned per 50M generations to limit the top memory need.
Parameters
mlock - mutex lock to distribute to child threads
wordlist - Reference to the wordlist file to write to
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
threads - number of OS threads to spawn
bFileIO - If false, filename will be ignored and will output to stdout.
Definition at line 225 of file modelMatrix.cpp.
                                                                                                                                                                {
    
    int iterationsPerThread = n/threads;
    int iterationsPerThreadCarryOver = n%threads;
    std::vector<std::thread*> threadsV;
    
    int id = 0;
    for(int i=0;i<threads;i++){
        threadsV.push_back(new std::thread(&Markov::API::ModelMatrix::FastRandomWalkThread, this, mlock, wordlist, iterationsPerThread, minLen, maxLen, id, bFileIO));
        id++;
    }
    threadsV.push_back(new std::thread(&Markov::API::ModelMatrix::FastRandomWalkThread, this, mlock, wordlist, iterationsPerThreadCarryOver, minLen, maxLen, id, bFileIO));
    for(int i=0;i<threads;i++){
        threadsV[i]->join();
    }
}
References Markov::API::ModelMatrix::FastRandomWalkThread().
Referenced by Markov::API::ModelMatrix::FastRandomWalk().
FastRandomWalkThread()
void Markov::API::ModelMatrix::FastRandomWalkThread (std::mutex * mlock, std::ofstream * wordlist, unsigned long int n, int minLen, int maxLen, int id, bool bFileIO) [protected], [inherited]
A single thread of a single partition of FastRandomWalk.
A FastRandomWalkPartition will initiate as many of this function as requested.
This function contains the bulk of the generation algorithm.
Parameters
mlock - mutex lock to distribute to child threads
wordlist - Reference to the wordlist file to write to
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
id - DEPRECATED Thread id - No longer used
bFileIO - If false, filename will be ignored and will output to stdout.
Definition at line 153 of file modelMatrix.cpp.
                                                                                                                                                        {
    if(n==0) return;
    Markov::Random::Marsaglia MarsagliaRandomEngine;
    char* e;
    char *res = new char[(maxLen+2)*n];
    int index = 0;
    char next;
    int len=0;
    long int selection;
    char cur;
    long int bufferctr = 0;
    for (int i = 0; i < n; i++) {
        cur=199;
        len=0;
        while (true) {
            e = strchr(this->matrixIndex, cur);
            index = e - this->matrixIndex;
            selection = MarsagliaRandomEngine.random() % this->totalEdgeWeights[index];
            for(int j=0;j<this->matrixSize;j++){
                selection -= this->valueMatrix[index][j];
                if (selection < 0){
                    next = this->edgeMatrix[index][j];
                    break;
                }
            }
            if (len >= maxLen) break;
            else if ((next < 0) && (len < minLen)) continue;
            else if (next < 0) break;
            cur = next;
            res[bufferctr + len++] = cur;
        }
        res[bufferctr + len++] = '\n';
        bufferctr+=len;
        
    }
    if(bFileIO){
        mlock->lock();
        *wordlist << res;
        mlock->unlock();
    }else{
        mlock->lock();
        std::cout << res;
        mlock->unlock();
    }
    delete res;
}
References Markov::API::ModelMatrix::edgeMatrix, Markov::API::ModelMatrix::matrixIndex, Markov::API::ModelMatrix::matrixSize, Markov::Random::Marsaglia::random(), Markov::API::ModelMatrix::totalEdgeWeights, and Markov::API::ModelMatrix::valueMatrix.
Referenced by Markov::API::ModelMatrix::FastRandomWalkPartition().
FlattenMatrix()
__host__ void Markov::API::CUDA::CUDAModelMatrix::FlattenMatrix ()
Flatten migrated matrix from 2d to 1d.
Definition at line 261 of file cudaModelMatrix.cu.
                                                             {
        this->flatEdgeMatrix = new char[this->matrixSize*this->matrixSize];
        this->flatValueMatrix = new long int[this->matrixSize*this->matrixSize];
        for(int i=0;i<this->matrixSize;i++){
            memcpy(&this->flatEdgeMatrix[i*this->matrixSize], this->edgeMatrix[i], this->matrixSize);
            memcpy(&this->flatValueMatrix[i*this->matrixSize], this->valueMatrix[i], this->matrixSize*sizeof(long int));
        }
    }
References flatEdgeMatrix, flatValueMatrix, and Markov::API::ModelMatrix::matrixSize.
GatherAsyncKernelOutput()
__host__ void Markov::API::CUDA::CUDAModelMatrix::GatherAsyncKernelOutput (int kernelID, bool bFileIO, std::ofstream & wordlist) [protected]
Definition at line 180 of file cudaModelMatrix.cu.
                                                                                                                        {
        cudaMemcpy(this->outputBuffer[kernelID],this->device_outputBuffer[kernelID],cudaPerKernelAllocationSize, cudaMemcpyDeviceToHost);
        //std::cerr << "Kernel" << kernelID << " output copied\n";
        if(bFileIO){
            for(long int j=0;j<cudaPerKernelAllocationSize;j+=cudaMemPerGrid){
                wordlist << &this->outputBuffer[kernelID][j];
            }
        }else{
            for(long int j=0;j<cudaPerKernelAllocationSize;j+=cudaMemPerGrid){
                std::cout << &this->outputBuffer[kernelID][j];
            }
        }
    }
References cudaMemPerGrid, cudaPerKernelAllocationSize, and outputBuffer.
Generate()
void Markov::API::MarkovPasswords::Generate (unsigned long int n, const char * wordlistFileName, int minLen = 6, int maxLen = 12, int threads = 20) [inherited]
Call Markov::Model::RandomWalk n times, and collect output.
Generate from model and write results to a file. a much more performance-optimized method. FastRandomWalk will reduce the runtime by %96.5 on average.
Deprecated
Deprecated See Markov::API::MatrixModel::FastRandomWalk for more information.
Parameters
n - Number of passwords to generate.
wordlistFileName - Filename to write to
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
threads - number of OS threads to spawn
Definition at line 118 of file markovPasswords.cpp.
                                                                                                                               {
    char* res;
    char print[100];
    std::ofstream wordlist;
    wordlist.open(wordlistFileName);
    std::mutex mlock;
    int iterationsPerThread = n/threads;
    int iterationsCarryOver = n%threads;
    std::vector<std::thread*> threadsV;
    for(int i=0;i<threads;i++){
        threadsV.push_back(new std::thread(&Markov::API::MarkovPasswords::GenerateThread, this, &mlock, iterationsPerThread, &wordlist, minLen, maxLen));
    }
    for(int i=0;i<threads;i++){
        threadsV[i]->join();
        delete threadsV[i];
    }
    this->GenerateThread(&mlock, iterationsCarryOver, &wordlist, minLen, maxLen);
    
}
References Markov::API::MarkovPasswords::GenerateThread().
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE(), and Markov::GUI::Generate::generation().
GenerateThread()
void Markov::API::MarkovPasswords::GenerateThread (std::mutex * outputLock, unsigned long int n, std::ofstream * wordlist, int minLen, int maxLen) [private], [inherited]
A single thread invoked by the Generate function.
DEPRECATED: See Markov::API::MatrixModel::FastRandomWalkThread for more information. This has been replaced with a much more performance-optimized method. FastRandomWalk will reduce the runtime by %96.5 on average.
Parameters
outputLock - shared mutex lock to lock during output operation. Prevents race condition on write.
n number of lines to be generated by this thread
wordlist wordlistfile
minLen - Minimum password length to generate
maxLen - Maximum password length to generate
Definition at line 140 of file markovPasswords.cpp.
                                                                                                                                       {
    char* res = new char[maxLen+5];
    if(n==0) return;
    Markov::Random::Marsaglia MarsagliaRandomEngine;
    for (int i = 0; i < n; i++) {
        this->RandomWalk(&MarsagliaRandomEngine, minLen, maxLen, res);
        outputLock->lock();
        *wordlist << res << "\n";
        outputLock->unlock();
    }
}
References Markov::Model< NodeStorageType >::RandomWalk().
Referenced by Markov::API::MarkovPasswords::Generate().
Import() [1/2]
void Markov::API::ModelMatrix::Import (const char * filename) [inherited]
Open a file to import with filename, and call bool Model::Import with std::ifstream.
Returns
True if successful, False for incomplete models or corrupt file formats
Example Use: Import a file with filename
Markov::Model<char> model;
model.Import("test.mdl");
 Construct the matrix when done.
Definition at line 19 of file modelMatrix.cpp.
                                                     {
    this->DeallocateMatrix();
    this->Markov::API::MarkovPasswords::Import(filename);
    this->ConstructMatrix();
}
References Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), and Markov::Model< NodeStorageType >::Import().
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE(), and main().
Import() [2/2]
bool Markov::Model< char >::Import (std::ifstream * f) [inherited]
Import a file to construct the model.
File contains a list of edges. For more info on the file format, check out the wiki and github readme pages. Format is: Left_repr;EdgeWeight;right_repr
Iterate over this list, and construct nodes and edges accordingly.
Returns
True if successful, False for incomplete models or corrupt file formats
Example Use: Import a file from ifstream
Markov::Model<char> model;
std::ifstream file("test.mdl");
model.Import(&file);
Definition at line 216 of file model.h.
                                                        {
    std::string cell;
    char src;
    char target;
    long int oc;
    while (std::getline(*f, cell)) {
        //std::cout << "cell: " << cell << std::endl;
        src = cell[0];
        target = cell[cell.length() - 1];
        char* j;
        oc = std::strtol(cell.substr(2, cell.length() - 2).c_str(),&j,10);
        //std::cout << oc << "\n";
        Markov::Node<NodeStorageType>* srcN;
        Markov::Node<NodeStorageType>* targetN;
        Markov::Edge<NodeStorageType>* e;
        if (this->nodes.find(src) == this->nodes.end()) {
            srcN = new Markov::Node<NodeStorageType>(src);
            this->nodes.insert(std::pair<char, Markov::Node<NodeStorageType>*>(src, srcN));
            //std::cout << "Creating new node at start.\n";
        }
        else {
            srcN = this->nodes.find(src)->second;
        }
        if (this->nodes.find(target) == this->nodes.end()) {
            targetN = new Markov::Node<NodeStorageType>(target);
            this->nodes.insert(std::pair<char, Markov::Node<NodeStorageType>*>(target, targetN));
            //std::cout << "Creating new node at end.\n";
        }
        else {
            targetN = this->nodes.find(target)->second;
        }
        e = srcN->Link(targetN);
        e->AdjustEdge(oc);
        this->edges.push_back(e);
        //std::cout << int(srcN->NodeValue()) << " --" << e->EdgeWeight() << "--> " << int(targetN->NodeValue()) << "\n";
    }
    this->OptimizeEdgeOrder();
    return true;
}
LaunchAsyncKernel()
__host__ void Markov::API::CUDA::CUDAModelMatrix::LaunchAsyncKernel (int kernelID, int minLen, int maxLen) [protected]
Definition at line 171 of file cudaModelMatrix.cu.
                                                                                                     {
        //if(kernelID == 0);// cudaStreamSynchronize(this->cudastreams[2]);
        //else cudaStreamSynchronize(this->cudastreams[kernelID-1]);
        FastRandomWalkCUDAKernel<<<cudaBlocks,cudaThreads,0, this->cudastreams[kernelID]>>>(iterationsPerKernelThread, minLen, maxLen, this->device_outputBuffer[kernelID], this->device_matrixIndex,
            this->device_totalEdgeWeights, this->device_valueMatrix, this->device_edgeMatrix, this->matrixSize, cudaMemPerGrid, this->device_seeds[kernelID]);
        //std::cerr << "Started kernel" << kernelID << "\n";
    }
ListCudaDevices()
__host__ void Markov::API::CUDA::CUDADeviceController::ListCudaDevices () [static], [inherited]
List CUDA devices in the system.
This function will print details of every CUDA capable device in the system.
Example output:
Device Number: 0
Device name: GeForce RTX 2070
Memory Clock Rate (KHz): 7001000
Memory Bus Width (bits): 256
Peak Memory Bandwidth (GB/s): 448.064
Max Linear Threads: 1024
Definition at line 16 of file cudaDeviceController.cu.
                                                                     { //list cuda Capable devices on host.
        int nDevices;
        cudaGetDeviceCount(&nDevices);
        for (int i = 0; i < nDevices; i++) {
            cudaDeviceProp prop;
            cudaGetDeviceProperties(&prop, i);
            std::cerr << "Device Number: " << i << "\n";
            std::cerr << "Device name: " << prop.name << "\n";
            std::cerr << "Memory Clock Rate (KHz): " << prop.memoryClockRate << "\n";
            std::cerr << "Memory Bus Width (bits): " << prop.memoryBusWidth << "\n";
            std::cerr << "Peak Memory Bandwidth (GB/s): " << 2.0 * prop.memoryClockRate * (prop.memoryBusWidth / 8) / 1.0e6 << "\n";
            std::cerr << "Max Linear Threads: " << prop.maxThreadsDim[0] << "\n";
            
        }
    }
MigrateMatrix()
__host__ void Markov::API::CUDA::CUDAModelMatrix::MigrateMatrix ()
Migrate the class members to the VRAM.
Cannot be used without calling Markov::API::ModelMatrix::ConstructMatrix at least once. This function will manage the memory allocation and data transfer from CPU RAM to GPU VRAM.
Newly allocated VRAM pointers are set in the class member variables.
Definition at line 20 of file cudaModelMatrix.cu.
                                                             {
        cudaError_t cudastatus;
        cudastatus = cudaMalloc((char**)&(this->device_matrixIndex),
            this->matrixSize*sizeof(char));
        CudaCheckNotifyErr(cudastatus, "Cuda failed to initialize device_matrixIndex.");
        cudastatus = cudaMalloc((long int **)&(this->device_totalEdgeWeights), this->matrixSize*sizeof(long int));
        CudaCheckNotifyErr(cudastatus, "Cuda failed to initialize device_totalEdgeWeights.");
        cudastatus = cudaMemcpy(this->device_matrixIndex, this->matrixIndex,
            this->matrixSize*sizeof(char), cudaMemcpyHostToDevice);
        CudaCheckNotifyErr(cudastatus, "Cuda failed to copy to device memory. (Index)");
        cudastatus = cudaMemcpy(this->device_totalEdgeWeights, this->totalEdgeWeights,
            this->matrixSize*sizeof(long int), cudaMemcpyHostToDevice);
        CudaCheckNotifyErr(cudastatus, "Cuda failed to copy to device memory. (Total Edge Values)");
        cudastatus = CudaMigrate2DFlat<char>(
            &(this->device_edgeMatrix), this->edgeMatrix, this->matrixSize, this->matrixSize);
        CudaCheckNotifyErr(cudastatus, " Cuda failed to initialize edge matrix.");
        cudastatus = CudaMigrate2DFlat<long int>(
            &(this->device_valueMatrix), this->valueMatrix, this->matrixSize, this->matrixSize);
        CudaCheckNotifyErr(cudastatus, " Cuda failed to initialize value matrix row.");
    }
Nodes()
std::map<char , Node<char >*>* Markov::Model< char >::Nodes () [inline], [inherited]
Return starter Node.
Returns
starter node with 00 NodeValue
Definition at line 181 of file model.h.
{ return &nodes;}
OpenDatasetFile()
std::ifstream * Markov::API::MarkovPasswords::OpenDatasetFile (const char * filename) [inherited]
Open dataset file and return the ifstream pointer.
Parameters
filename - Filename to open
Returns
ifstream* to the the dataset file
Definition at line 51 of file markovPasswords.cpp.
                                                                          {
    std::ifstream* datasetFile;
    std::ifstream newFile(filename);
    datasetFile = &newFile;
    this->Import(datasetFile);
    return datasetFile;
}
References Markov::Model< NodeStorageType >::Import().
OptimizeEdgeOrder()
void Markov::Model< char >::OptimizeEdgeOrder [inherited]
Sort edges of all nodes in the model ordered by edge weights.
Definition at line 265 of file model.h.
                                                    {
    for (std::pair<unsigned char, Markov::Node<NodeStorageType>*> const& x : this->nodes) {
        //std::cout << "Total edges in EdgesV: " << x.second->edgesV.size() << "\n";
        std::sort (x.second->edgesV.begin(), x.second->edgesV.end(), [](Edge<NodeStorageType> *lhs, Edge<NodeStorageType> *rhs)->bool{
            return lhs->EdgeWeight() > rhs->EdgeWeight();
        });
        //for(int i=0;i<x.second->edgesV.size();i++)
        // std::cout << x.second->edgesV[i]->EdgeWeight() << ", ";
        //std::cout << "\n";
    }
    //std::cout << "Total number of nodes: " << this->nodes.size() << std::endl;
    //std::cout << "Total number of edges: " << this->edges.size() << std::endl;
}
prepKernelMemoryChannel()
__host__ void Markov::API::CUDA::CUDAModelMatrix::prepKernelMemoryChannel (int numberOfStreams) [protected]
Definition at line 145 of file cudaModelMatrix.cu.
                                                                                          {
        
        this->cudastreams = new cudaStream_t[numberOfStreams];
        for(int i=0;i<numberOfStreams;i++)
            cudaStreamCreate(&this->cudastreams[i]);
        this-> outputBuffer = new char*[numberOfStreams];
        for(int i=0;i<numberOfStreams;i++)
            this->outputBuffer[i]= new char[cudaPerKernelAllocationSize];
        cudaError_t cudastatus;
        this-> device_outputBuffer = new char*[numberOfStreams];
            for(int i=0;i<numberOfStreams;i++){
                cudastatus = cudaMalloc((char**)&(device_outputBuffer[i]), cudaPerKernelAllocationSize);
                CudaCheckNotifyErr(cudastatus, "Failed to establish memory channel. Possibly out of VRAM?");
            }
        this-> device_seeds = new unsigned long*[numberOfStreams];
        for(int i=0;i<numberOfStreams;i++){
            Markov::API::CUDA::Random::Marsaglia *MEarr = new Markov::API::CUDA::Random::Marsaglia[cudaGridSize];
            this->device_seeds[i] = Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM(MEarr, cudaGridSize);
            delete[] MEarr;
        }
    }
References cudaGridSize, cudaPerKernelAllocationSize, device_outputBuffer, device_seeds, Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM(), and outputBuffer.
RandomWalk()
char * Markov::Model< char >::RandomWalk (Markov::Random::RandomEngine * randomEngine, int minSetting, int maxSetting, NodeStorageType * buffer) [inherited]
Do a random walk on this model.
Start from the starter node, on each node, invoke RandomNext using the random engine on current node, until terminator node is reached. If terminator node is reached before minimum length criateria is reached, ignore the last selection and re-invoke randomNext
If maximum length criteria is reached but final node is not, cut off the generation and proceed to the final node. This function takes Markov::Random::RandomEngine as a parameter to generate pseudo random numbers from
This library is shipped with two random engines, Marsaglia and Mersenne. While mersenne output is higher in entropy, most use cases don't really need super high entropy output, so Markov::Random::Marsaglia is preferable for better performance.
This function WILL NOT reallocate buffer. Make sure no out of bound writes are happening via maximum length criteria.
Example Use: Generate 10 lines, with 5 to 10 characters, and print the output. Use Marsaglia
Markov::Model<char> model;
Model.import("model.mdl");
char* res = new char[11];
Markov::Random::Marsaglia MarsagliaRandomEngine;
for (int i = 0; i < 10; i++) {
    this->RandomWalk(&MarsagliaRandomEngine, 5, 10, res);
    std::cout << res << "\n";
 }
Parameters
randomEngine Random Engine to use for the random walks. For examples, see Markov::Random::Mersenne and Markov::Random::Marsaglia
minSetting Minimum number of characters to generate
maxSetting Maximum number of character to generate
buffer buffer to write the result to
Returns
Null terminated string that was generated.
Definition at line 307 of file model.h.
                                                                                                                                                         {
    Markov::Node<NodeStorageType>* n = this->starterNode;
    int len = 0;
    Markov::Node<NodeStorageType>* temp_node;
    while (true) {
        temp_node = n->RandomNext(randomEngine);
        if (len >= maxSetting) {
            break;
        }
        else if ((temp_node == NULL) && (len < minSetting)) {
            continue;
        }
        else if (temp_node == NULL){
            break;
        }
            
        n = temp_node;
        buffer[len++] = n->NodeValue();
    }
    //null terminate the string
    buffer[len] = 0x00;
    //do something with the generated string
    return buffer; //for now
}
Save()
std::ofstream * Markov::API::MarkovPasswords::Save (const char * filename) [inherited]
Export model to file.
Parameters
filename - Export filename.
Returns
std::ofstream* of the exported file.
Definition at line 106 of file markovPasswords.cpp.
                                                                {
    std::ofstream* exportFile;
    std::ofstream newFile(filename);
    exportFile = &newFile;
    
    this->Export(exportFile);
    return exportFile;
}
References Markov::Model< NodeStorageType >::Export().
StarterNode()
Node<char >* Markov::Model< char >::StarterNode () [inline], [inherited]
Return starter Node.
Returns
starter node with 00 NodeValue
Definition at line 171 of file model.h.
{ return starterNode;}
Train()
void Markov::API::ModelMatrix::Train (const char * datasetFileName, char delimiter, int threads) [inherited]
Train the model with the dataset file.
Parameters
datasetFileName - Ifstream* to the dataset. If null, use class member
delimiter - a character, same as the delimiter in dataset content
threads - number of OS threads to spawn
Markov::API::MarkovPasswords mp;
mp.Import("models/2gram.mdl");
mp.Train("password.corpus");
 Construct the matrix when done.
Definition at line 25 of file modelMatrix.cpp.
                                                                                        {
    this->DeallocateMatrix();
    this->Markov::API::MarkovPasswords::Train(datasetFileName,delimiter,threads);
    this->ConstructMatrix();
}
References Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), and Markov::API::MarkovPasswords::Train().
Referenced by Markov::Markopy::BOOST_PYTHON_MODULE().
TrainThread()
void Markov::API::MarkovPasswords::TrainThread (Markov::API::Concurrency::ThreadSharedListHandler * listhandler, char delimiter) [private], [inherited]
A single thread invoked by the Train function.
Parameters
listhandler - Listhandler class to read corpus from
delimiter - a character, same as the delimiter in dataset content
Definition at line 85 of file markovPasswords.cpp.
                                                                                                                  {
    char format_str[] ="%ld,%s";
    format_str[3]=delimiter;
    std::string line;
    while (listhandler->next(&line) && keepRunning) {
        long int oc;
        if (line.size() > 100) {
            line = line.substr(0, 100);
        }
        char* linebuf = new char[line.length()+5];
#ifdef _WIN32
        sscanf_s(line.c_str(), "%ld,%s", &oc, linebuf, line.length()+5); //<== changed format_str to-> "%ld,%s"
#else
        sscanf(line.c_str(), format_str, &oc, linebuf);
#endif
        this->AdjustEdge((const char*)linebuf, oc);
        delete linebuf;
    }
}
References Markov::Model< NodeStorageType >::AdjustEdge(), keepRunning, and Markov::API::Concurrency::ThreadSharedListHandler::next().
Referenced by Markov::API::MarkovPasswords::Train().
Member Data Documentation
alternatingKernels
int Markov::API::CUDA::CUDAModelMatrix::alternatingKernels [private]
Definition at line 135 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
cudaBlocks
int Markov::API::CUDA::CUDAModelMatrix::cudaBlocks [private]
Definition at line 125 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
cudaGridSize
int Markov::API::CUDA::CUDAModelMatrix::cudaGridSize [private]
Definition at line 131 of file cudaModelMatrix.h.
Referenced by FastRandomWalk(), and prepKernelMemoryChannel().
cudaMemPerGrid
int Markov::API::CUDA::CUDAModelMatrix::cudaMemPerGrid [private]
Definition at line 132 of file cudaModelMatrix.h.
Referenced by FastRandomWalk(), and GatherAsyncKernelOutput().
cudaPerKernelAllocationSize
long int Markov::API::CUDA::CUDAModelMatrix::cudaPerKernelAllocationSize [private]
Definition at line 133 of file cudaModelMatrix.h.
Referenced by FastRandomWalk(), GatherAsyncKernelOutput(), and prepKernelMemoryChannel().
cudastreams
cudaStream_t* Markov::API::CUDA::CUDAModelMatrix::cudastreams [private]
Definition at line 139 of file cudaModelMatrix.h.
cudaThreads
int Markov::API::CUDA::CUDAModelMatrix::cudaThreads [private]
Definition at line 126 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
datasetFile
std::ifstream* Markov::API::MarkovPasswords::datasetFile [private], [inherited]
Definition at line 123 of file markovPasswords.h.
device_edgeMatrix
char* Markov::API::CUDA::CUDAModelMatrix::device_edgeMatrix [private]
VRAM Address pointer of edge matrix (from modelMatrix.h)
Definition at line 88 of file cudaModelMatrix.h.
device_matrixIndex
char* Markov::API::CUDA::CUDAModelMatrix::device_matrixIndex [private]
VRAM Address pointer of matrixIndex (from modelMatrix.h)
Definition at line 98 of file cudaModelMatrix.h.
device_outputBuffer
char** Markov::API::CUDA::CUDAModelMatrix::device_outputBuffer [private]
RandomWalk results in device.
Definition at line 108 of file cudaModelMatrix.h.
Referenced by prepKernelMemoryChannel().
device_seeds
unsigned long** Markov::API::CUDA::CUDAModelMatrix::device_seeds [private]
Definition at line 137 of file cudaModelMatrix.h.
Referenced by prepKernelMemoryChannel().
device_totalEdgeWeights
long int* Markov::API::CUDA::CUDAModelMatrix::device_totalEdgeWeights [private]
VRAM Address pointer of total edge weights (from modelMatrix.h)
Definition at line 103 of file cudaModelMatrix.h.
device_valueMatrix
long int* Markov::API::CUDA::CUDAModelMatrix::device_valueMatrix [private]
VRAM Address pointer of value matrix (from modelMatrix.h)
Definition at line 93 of file cudaModelMatrix.h.
edgeMatrix
char** Markov::API::ModelMatrix::edgeMatrix [protected], [inherited]
2-D Character array for the edge Matrix (The characters of Nodes)
Definition at line 175 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), Markov::API::ModelMatrix::DumpJSON(), and Markov::API::ModelMatrix::FastRandomWalkThread().
edges
std::vector<Edge<char >*> Markov::Model< char >::edges [private], [inherited]
A list of all edges in this model.
Definition at line 204 of file model.h.
flatEdgeMatrix
char* Markov::API::CUDA::CUDAModelMatrix::flatEdgeMatrix [private]
Adding Edge matrix end-to-end and resize to 1-D array for better perfomance on traversing.
Definition at line 118 of file cudaModelMatrix.h.
Referenced by FlattenMatrix().
flatValueMatrix
long int* Markov::API::CUDA::CUDAModelMatrix::flatValueMatrix [private]
Adding Value matrix end-to-end and resize to 1-D array for better perfomance on traversing.
Definition at line 123 of file cudaModelMatrix.h.
Referenced by FlattenMatrix().
iterationsPerKernelThread
int Markov::API::CUDA::CUDAModelMatrix::iterationsPerKernelThread [private]
Definition at line 127 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
matrixIndex
char* Markov::API::ModelMatrix::matrixIndex [protected], [inherited]
to hold the Matrix index (To hold the orders of 2-D arrays')
Definition at line 190 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), Markov::API::ModelMatrix::DumpJSON(), and Markov::API::ModelMatrix::FastRandomWalkThread().
matrixSize
int Markov::API::ModelMatrix::matrixSize [protected], [inherited]
to hold Matrix size
Definition at line 185 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), Markov::API::ModelMatrix::DumpJSON(), Markov::API::ModelMatrix::FastRandomWalkThread(), and FlattenMatrix().
modelSavefile
std::ofstream* Markov::API::MarkovPasswords::modelSavefile [private], [inherited]
Dataset file input of our system
Definition at line 124 of file markovPasswords.h.
nodes
std::map<char , Node<char >*> Markov::Model< char >::nodes [private], [inherited]
Map LeftNode is the Nodes NodeValue Map RightNode is the node pointer.
Definition at line 193 of file model.h.
numberOfPartitions
int Markov::API::CUDA::CUDAModelMatrix::numberOfPartitions [private]
Definition at line 130 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
outputBuffer
char** Markov::API::CUDA::CUDAModelMatrix::outputBuffer [private]
RandomWalk results in host.
Definition at line 113 of file cudaModelMatrix.h.
Referenced by GatherAsyncKernelOutput(), and prepKernelMemoryChannel().
outputFile
std::ofstream* Markov::API::MarkovPasswords::outputFile [private], [inherited]
File to save model of our system
Definition at line 125 of file markovPasswords.h.
ready
bool Markov::API::ModelMatrix::ready [protected], [inherited]
True when matrix is constructed. False if not.
Definition at line 200 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), and Markov::API::ModelMatrix::ModelMatrix().
starterNode
Node<char >* Markov::Model< char >::starterNode [private], [inherited]
Starter Node of this model.
Definition at line 198 of file model.h.
totalEdgeWeights
long int* Markov::API::ModelMatrix::totalEdgeWeights [protected], [inherited]
Array of the Total Edge Weights.
Definition at line 195 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), and Markov::API::ModelMatrix::FastRandomWalkThread().
totalOutputPerKernel
long int Markov::API::CUDA::CUDAModelMatrix::totalOutputPerKernel [private]
Definition at line 129 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
totalOutputPerSync
long int Markov::API::CUDA::CUDAModelMatrix::totalOutputPerSync [private]
Definition at line 128 of file cudaModelMatrix.h.
Referenced by FastRandomWalk().
valueMatrix
long int** Markov::API::ModelMatrix::valueMatrix [protected], [inherited]
2-d Integer array for the value Matrix (For the weights of Edges)
Definition at line 180 of file modelMatrix.h.
Referenced by Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DeallocateMatrix(), Markov::API::ModelMatrix::DumpJSON(), and Markov::API::ModelMatrix::FastRandomWalkThread().
The documentation for this class was generated from the following files:
cudaModelMatrix.h
cudaModelMatrix.cu