Markov::Random::Marsaglia Class Reference
Implementation of Marsaglia Random Engine.
#include <random.h>
Public Member Functions
Marsaglia ()
Construct Marsaglia Engine.
unsigned long random ()
Generate Random Number.
Public Attributes
unsigned long x
unsigned long y
unsigned long z
Protected Member Functions
std::random_device & rd ()
Default random device for seeding.
std::default_random_engine & generator ()
Default random engine for seeding.
std::uniform_int_distribution< long long unsigned > & distribution ()
Distribution schema for seeding.
Detailed Description
Implementation of Marsaglia Random Engine.
This is an implementation of Marsaglia Random engine, which for most use cases is a better fit than other solutions. Very simple mathematical formula to generate pseudorandom integer, so its crazy fast.
This implementation of the Marsaglia Engine is seeded by random.h default random engine. RandomEngine is only seeded once so its not a performance issue.
Example Use: Using Marsaglia Engine with RandomWalk
Markov::Model<char> model;
Model.import("model.mdl");
char* res = new char[11];
Markov::Random::Marsaglia MarsagliaRandomEngine;
for (int i = 0; i < 10; i++) {
    this->RandomWalk(&MarsagliaRandomEngine, 5, 10, res);
    std::cout << res << "\n";
 }
Example Use: Generating a random number with Marsaglia Engine
Markov::Random::Marsaglia me;
std::cout << me.random();
Definition at line 116 of file random.h.
Constructor & Destructor Documentation
Marsaglia()
Markov::Random::Marsaglia::Marsaglia () [inline]
Construct Marsaglia Engine.
Initialize x,y and z using the default random engine.
Definition at line 123 of file random.h.
                   {
            this->x = this->distribution()(this->generator());
            this->y = this->distribution()(this->generator());
            this->z = this->distribution()(this->generator());
            //std::cout << "x: " << x << ", y: " << y << ", z: " << z << "\n";
        }
References Markov::Random::DefaultRandomEngine::distribution(), Markov::Random::DefaultRandomEngine::generator(), x, y, and z.
Member Function Documentation
distribution()
std::uniform_int_distribution<long long unsigned>& Markov::Random::DefaultRandomEngine::distribution () [inline], [protected], [inherited]
Distribution schema for seeding.
Definition at line 81 of file random.h.
                                                                               {
            static std::uniform_int_distribution<long long unsigned> _distribution(0, 0xffffFFFF);
            return _distribution;
        }
Referenced by Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
generator()
std::default_random_engine& Markov::Random::DefaultRandomEngine::generator () [inline], [protected], [inherited]
Default random engine for seeding.
Definition at line 73 of file random.h.
                                                     {
            static std::default_random_engine _generator(rd()());
            return _generator;
        }
References Markov::Random::DefaultRandomEngine::rd().
Referenced by Marsaglia(), and Markov::Random::DefaultRandomEngine::random().
random()
unsigned long Markov::Random::Marsaglia::random () [inline], [virtual]
Generate Random Number.
Returns
random number in long range.
Reimplemented from Markov::Random::DefaultRandomEngine.
Definition at line 131 of file random.h.
                                 {
        unsigned long t;
        x ^= x << 16;
        x ^= x >> 5;
        x ^= x << 1;
        t = x;
        x = y;
        y = z;
        z = t ^ x ^ y;
        return z;
    }
References x, y, and z.
Referenced by Markov::API::ModelMatrix::FastRandomWalkThread().
rd()
std::random_device& Markov::Random::DefaultRandomEngine::rd () [inline], [protected], [inherited]
Default random device for seeding.
Definition at line 65 of file random.h.
                                      {
            static std::random_device _rd;
            return _rd;
        }
Referenced by Markov::Random::DefaultRandomEngine::generator().
Member Data Documentation
x
unsigned long Markov::Random::Marsaglia::x
Definition at line 146 of file random.h.
Referenced by Marsaglia(), Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM(), and random().
y
unsigned long Markov::Random::Marsaglia::y
Definition at line 147 of file random.h.
Referenced by Marsaglia(), Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM(), and random().
z
unsigned long Markov::Random::Marsaglia::z
Definition at line 148 of file random.h.
Referenced by Marsaglia(), Markov::API::CUDA::Random::Marsaglia::MigrateToVRAM(), and random().
The documentation for this class was generated from the following file:
random.h