Markov::API::CUDA::CUDADeviceController Class Reference
Controller class for CUDA device.
#include <cudaDeviceController.h>
Static Public Member Functions
static __host__ void ListCudaDevices ()
List CUDA devices in the system.
Static Protected Member Functions
static __host__ int CudaCheckNotifyErr (cudaError_t _status, const char *msg, bool bExit=true)
Check results of the last operation on GPU.
template<typename T >
static __host__ cudaError_t CudaMalloc2DToFlat (T **dst, int row, int col)
Malloc a 2D array in device space.
template<typename T >
static __host__ cudaError_t CudaMemcpy2DToFlat (T *dst, T **src, int row, int col)
Memcpy a 2D array in device space after flattening.
template<typename T >
static __host__ cudaError_t CudaMigrate2DFlat (T **dst, T **src, int row, int col)
Both malloc and memcpy a 2D array into device VRAM.
Detailed Description
Controller class for CUDA device.
This implementation only supports Nvidia devices.
Definition at line 18 of file cudaDeviceController.h.
Member Function Documentation
CudaCheckNotifyErr()
__host__ int Markov::API::CUDA::CUDADeviceController::CudaCheckNotifyErr (cudaError_t _status, const char * msg, bool bExit = true) [static], [protected]
Check results of the last operation on GPU.
Check the status returned from cudaMalloc/cudaMemcpy to find failures.
If a failure occurs, its assumed beyond redemption, and exited.
Parameters
_status Cuda error status to check
msg Message to print in case of a failure
Returns
0 if successful, 1 if failure. Example output:
char *da, a = "test";
cudastatus = cudaMalloc((char **)&da, 5*sizeof(char*));
CudaCheckNotifyErr(cudastatus, "Failed to allocate VRAM for *da.\n");
Definition at line 32 of file cudaDeviceController.cu.
                                                                                                                       {
        if (_status != cudaSuccess) {
            std::cerr << "\033[1;31m" << msg << " -> " << cudaGetErrorString(_status) << " ("<< _status << ")" << "\033[0m" << "\n";
            
            if(bExit) {
                cudaDeviceReset();
                exit(1);
            }
        }
        return 0;
    }
CudaMalloc2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMalloc2DToFlat (T ** dst, int row, int col) [inline], [static], [protected]
Malloc a 2D array in device space.
This function will allocate enough space on VRAM for flattened 2D array.
Parameters
dst destination pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
if(cudastatus!=cudaSuccess){
    CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
}
Definition at line 75 of file cudaDeviceController.h.
                                                                                 {
            cudaError_t cudastatus = cudaMalloc((T **)dst, row*col*sizeof(T));
            CudaCheckNotifyErr(cudastatus, "cudaMalloc Failed.", false);
            return cudastatus;
        }
References CudaMigrate2DFlat().
CudaMemcpy2DToFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMemcpy2DToFlat (T * dst, T ** src, int row, int col) [inline], [static], [protected]
Memcpy a 2D array in device space after flattening.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMalloc2DToFlat<char>(&dst, 5, 15);
CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
cudastatus = CudaMemcpy2DToFlat<char>(*dst,src,15,15);
CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
Definition at line 103 of file cudaDeviceController.h.
                                                                                         {
            T* tempbuf = new T[row*col];
            for(int i=0;i<row;i++){
                memcpy(&(tempbuf[row*i]), src[i], col);
            }
            return cudaMemcpy(dst, tempbuf, row*col*sizeof(T), cudaMemcpyHostToDevice);
            
        }
References CudaMigrate2DFlat().
CudaMigrate2DFlat()
template<typename T >
static __host__ cudaError_t Markov::API::CUDA::CUDADeviceController::CudaMigrate2DFlat (T ** dst, T ** src, int row, int col) [inline], [static], [protected]
Both malloc and memcpy a 2D array into device VRAM.
Resulting buffer will not be true 2D array.
Parameters
dst destination pointer
rc source pointer
row row size of the 2d array
col column size of the 2d array
Returns
cudaError_t status of the cudaMalloc operation
Example output:
cudaError_t cudastatus;
char* dst;
cudastatus = CudaMigrate2DFlat<long int>(
   &dst, this->valueMatrix, this->matrixSize, this->matrixSize);
CudaCheckNotifyErr(cudastatus, " Cuda failed to initialize value matrix row.");
Definition at line 132 of file cudaDeviceController.h.
                                                                                         {
            cudaError_t cudastatus;
            cudastatus = CudaMalloc2DToFlat<T>(dst, row, col);
            if(cudastatus!=cudaSuccess){
                CudaCheckNotifyErr(cudastatus, " CudaMalloc2DToFlat Failed.", false);
                return cudastatus;
            }
            cudastatus = CudaMemcpy2DToFlat<T>(*dst,src,row,col);
            CudaCheckNotifyErr(cudastatus, " CudaMemcpy2DToFlat Failed.", false);
            return cudastatus;
        }
References CudaMigrate2DFlat().
Referenced by CudaMalloc2DToFlat(), CudaMemcpy2DToFlat(), and CudaMigrate2DFlat().
ListCudaDevices()
__host__ void Markov::API::CUDA::CUDADeviceController::ListCudaDevices () [static]
List CUDA devices in the system.
This function will print details of every CUDA capable device in the system.
Example output:
Device Number: 0
Device name: GeForce RTX 2070
Memory Clock Rate (KHz): 7001000
Memory Bus Width (bits): 256
Peak Memory Bandwidth (GB/s): 448.064
Max Linear Threads: 1024
Definition at line 16 of file cudaDeviceController.cu.
                                                                     { //list cuda Capable devices on host.
        int nDevices;
        cudaGetDeviceCount(&nDevices);
        for (int i = 0; i < nDevices; i++) {
            cudaDeviceProp prop;
            cudaGetDeviceProperties(&prop, i);
            std::cerr << "Device Number: " << i << "\n";
            std::cerr << "Device name: " << prop.name << "\n";
            std::cerr << "Memory Clock Rate (KHz): " << prop.memoryClockRate << "\n";
            std::cerr << "Memory Bus Width (bits): " << prop.memoryBusWidth << "\n";
            std::cerr << "Peak Memory Bandwidth (GB/s): " << 2.0 * prop.memoryClockRate * (prop.memoryBusWidth / 8) / 1.0e6 << "\n";
            std::cerr << "Max Linear Threads: " << prop.maxThreadsDim[0] << "\n";
            
        }
    }
The documentation for this class was generated from the following files:
Markopy/CudaMarkovAPI/src/cudaDeviceController.h
Markopy/CudaMarkovAPI/src/cudaDeviceController.cu