Markov::GUI::Generate Class Reference
QT Generation page class.
#include <Generate.h>
Public Slots
void home ()
void generation ()
void train ()
void vis ()
Public Member Functions
Generate (QWidget *parent=Q_NULLPTR)
Private Attributes
Ui::Generate ui
Detailed Description
QT Generation page class.
Definition at line 15 of file Generate.h.
Constructor & Destructor Documentation
Generate()
Generate::Generate (QWidget * parent = Q_NULLPTR)
Definition at line 20 of file Generate.cpp.
    : QMainWindow(parent)
{
    ui.setupUi(this);
    QObject::connect(ui.pushButton, &QPushButton::clicked, this, [this] {generation(); });
    QObject::connect(ui.pushButton_4, &QPushButton::clicked, this, [this] {home(); });
    QObject::connect(ui.pushButton_3, &QPushButton::clicked, this, [this] {train(); });
    QObject::connect(ui.pushButton_2, &QPushButton::clicked, this, [this] {vis(); });
    ui.pushButton->setVisible(false);
    ui.lineEdit->setVisible(false);
    ui.lineEdit_2->setVisible(false);
    ui.lineEdit_3->setVisible(false);
    ui.label_3->setVisible(false);
    ui.label_4->setVisible(false);
    ui.label_5->setVisible(false);
}
References ui.
Member Function Documentation
generation
void Generate::generation () [slot]
Definition at line 42 of file Generate.cpp.
                          {
   
    QString file_name = QFileDialog::getOpenFileName(this, "Open a File", QDir::homePath());
    QFile file(file_name);
    
    int numberPass = ui.lineEdit->text().toInt();
    int minLen = ui.lineEdit_2->text().toInt();
    int maxLen = ui.lineEdit_3->text().toInt();
    char* cstr;
    std::string fname = file_name.toStdString();
    cstr = new char[fname.size() + 1];
    strcpy(cstr, fname.c_str());
    
    ui.label_6->setText("GENERATING!");
    
    Markov::API::MarkovPasswords mp;
    mp.Import("src\\CLI\\sample_models\\2gram-trained.mdl");
    mp.Generate(numberPass,cstr,minLen,maxLen);
    if (!file.open(QFile::ReadOnly | QFile::Text)) {
        QMessageBox::warning(this, "Error", "File Not Open!");
    }
    QTextStream in(&file);
    QString text = in.readAll();
    ui.plainTextEdit->setPlainText(text);
    
    ui.label_6->setText("DONE!");
    
    
   
    file.close();
}
References Markov::API::MarkovPasswords::Generate(), and ui.
home
void Generate::home () [slot]
Definition at line 121 of file Generate.cpp.
                    {
     CLI* w = new CLI;
     w->show();
     this->close();
}
train
void Generate::train () [slot]
Definition at line 82 of file Generate.cpp.
                     {
    QString file_name = QFileDialog::getOpenFileName(this, "Open a File", QDir::homePath());
    QFile file(file_name);
    if (!file.open(QFile::ReadOnly | QFile::Text)) {
        QMessageBox::warning(this, "Error", "File Not Open!");
    }
    QTextStream in(&file);
    QString text = in.readAll();
    char* cstr;
    std::string fname = file_name.toStdString();
    cstr = new char[fname.size() + 1];
    strcpy(cstr, fname.c_str());
    char a = ',';
    Markov::API::MarkovPasswords mp;
    mp.Import("models\\2gram.mdl");
    mp.Train(cstr, a,10);
    mp.Export("models\\finished.mdl");
    ui.pushButton->setVisible(true);
    ui.lineEdit->setVisible(true);
    ui.lineEdit_2->setVisible(true);
    ui.lineEdit_3->setVisible(true);
    ui.label_3->setVisible(true);
    ui.label_4->setVisible(true);
    ui.label_5->setVisible(true);
    file.close();
}
References Markov::API::MarkovPasswords::Train(), and ui.
Referenced by Python.Markopy.BaseCLI::process().
vis
void Generate::vis () [slot]
Definition at line 126 of file Generate.cpp.
                     {
    MarkovPasswordsGUI* w = new MarkovPasswordsGUI;
    w->show();
    this->close();
}
Member Data Documentation
ui
Ui::Generate Markov::GUI::Generate::ui [private]
Definition at line 21 of file Generate.h.
Referenced by Generate(), generation(), and train().
The documentation for this class was generated from the following files:
Markopy/MarkovPasswordsGUI/src/Generate.h
Markopy/MarkovPasswordsGUI/src/Generate.cpp