Testing::MarkovModel Namespace Reference
Testing namespace for MarkovModel.
Functions
TEST_CLASS (Edge)
Test class for rest of Edge cases.
TEST_CLASS (Node)
Test class for rest of Node cases.
TEST_CLASS (Model)
Test class for rest of model cases.
Detailed Description
Testing namespace for MarkovModel.
Function Documentation
TEST_CLASS() [1/3]
Testing::MarkovModel::TEST_CLASS (Edge)
Test class for rest of Edge cases.
send exception on integer underflow
test integer overflows
Definition at line 494 of file UnitTests.cpp.
        {
        public:
            TEST_METHOD(except_integer_underflow) {
                auto _underflow_adjust = [] {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    e->AdjustEdge(15);
                    e->AdjustEdge(-30);
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                };
                Assert::ExpectException<std::underflow_error>(_underflow_adjust);
            }
            TEST_METHOD(except_integer_overflow) {
                auto _overflow_adjust = [] {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    e->AdjustEdge(~0ull);
                    e->AdjustEdge(1);
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                };
                Assert::ExpectException<std::underflow_error>(_overflow_adjust);
            }
        };
References TEST_CLASS().
TEST_CLASS() [2/3]
Testing::MarkovModel::TEST_CLASS (Model)
Test class for rest of model cases.
Definition at line 592 of file UnitTests.cpp.
        {
        public:
            TEST_METHOD(functional_random_walk) {
                unsigned char* res2 = new unsigned char[12 + 5];
                Markov::Random::Marsaglia MarsagliaRandomEngine;
                Markov::Model<unsigned char> m;
                Markov::Node<unsigned char>* starter = m.StarterNode();
                Markov::Node<unsigned char>* a = new Markov::Node<unsigned char>('a');
                Markov::Node<unsigned char>* b = new Markov::Node<unsigned char>('b');
                Markov::Node<unsigned char>* c = new Markov::Node<unsigned char>('c');
                Markov::Node<unsigned char>* end = new Markov::Node<unsigned char>(0xff);
                starter->Link(a)->AdjustEdge(1);
                a->Link(b)->AdjustEdge(1);
                b->Link(c)->AdjustEdge(1);
                c->Link(end)->AdjustEdge(1);
                char* res = (char*)m.RandomWalk(&MarsagliaRandomEngine,1,12,res2);
                Assert::IsFalse(strcmp(res, "abc"));
            }
            TEST_METHOD(functionoal_random_walk_without_any) {
                Markov::Model<unsigned char> m;
                Markov::Node<unsigned char>* starter = m.StarterNode();
                Markov::Node<unsigned char>* a = new Markov::Node<unsigned char>('a');
                Markov::Node<unsigned char>* b = new Markov::Node<unsigned char>('b');
                Markov::Node<unsigned char>* c = new Markov::Node<unsigned char>('c');
                Markov::Node<unsigned char>* end = new Markov::Node<unsigned char>(0xff);
                Markov::Edge<unsigned char>* res = NULL;
                starter->Link(a)->AdjustEdge(1);
                a->Link(b)->AdjustEdge(1);
                b->Link(c)->AdjustEdge(1);
                c->Link(end)->AdjustEdge(1);
                res = starter->FindEdge('D');
                Assert::IsNull(res);
            }
        };
References TEST_CLASS().
Referenced by TEST_CLASS().
TEST_CLASS() [3/3]
Testing::MarkovModel::TEST_CLASS (Node)
Test class for rest of Node cases.
test RandomNext with 64 bit high values
test RandomNext with 64 bit high values
randomNext when no edges are present
Definition at line 532 of file UnitTests.cpp.
        {
        public:
            TEST_METHOD(rand_next_u64) {
                Markov::Random::Marsaglia MarsagliaRandomEngine;
                Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                Markov::Edge<unsigned char>* e = src->Link(target1);
                e->AdjustEdge((unsigned long)(1ull << 63));
                Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                Assert::IsTrue(res == target1);
                delete src;
                delete target1;
                delete e;
            }
            TEST_METHOD(rand_next_u64_max) {
                Markov::Random::Marsaglia MarsagliaRandomEngine;
                Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                Markov::Edge<unsigned char>* e = src->Link(target1);
                e->AdjustEdge((0xffffFFFF));
                Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                Assert::IsTrue(res == target1);
                delete src;
                delete target1;
                delete e;
            }
            TEST_METHOD(uninitialized_rand_next) {
                auto _invalid_next = [] {
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(src, target1);
                    Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                    delete src;
                    delete target1;
                    delete e;
                };
                Assert::ExpectException<std::logic_error>(_invalid_next);
            }
        };
References TEST_CLASS().