Markov::Markopy::CUDA Namespace Reference
CPython module for Markov::API::CUDA objects.
Functions
BOOST_PYTHON_MODULE (cudamarkopy)
Detailed Description
CPython module for Markov::API::CUDA objects.
Function Documentation
BOOST_PYTHON_MODULE()
Markov::Markopy::CUDA::BOOST_PYTHON_MODULE (cudamarkopy)
Definition at line 20 of file cudaMarkopy.cu.
    {
        bool (Markov::API::MarkovPasswords::*Export)(const char*) = &Markov::Model<char>::Export;
        void (Markov::API::CUDA::CUDAModelMatrix::*FastRandomWalk)(unsigned long int, const char*, int, int, bool, bool) = &Markov::API::CUDA::CUDAModelMatrix::FastRandomWalk;
        class_<Markov::API::CUDA::CUDAModelMatrix>("CUDAModelMatrix", init<>())
            
            .def(init<>())
            .def("Train", &Markov::API::ModelMatrix::Train)
            .def("Import", &Markov::API::ModelMatrix::Import, "Import a model file.")
            .def("Export", Export, "Export a model to file.")
            .def("ConstructMatrix",&Markov::API::ModelMatrix::ConstructMatrix)
            .def("DumpJSON",&Markov::API::ModelMatrix::DumpJSON)
            .def("FastRandomWalk", FastRandomWalk)
            ;
    };
References Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DumpJSON(), Markov::Model< NodeStorageType >::Export(), Markov::API::ModelMatrix::Import(), and Markov::API::ModelMatrix::Train().