Testing::MVP::MarkovModel Namespace Reference
Testing Namespace for MVP MarkovModel.
Functions
TEST_CLASS (Edge)
Test class for minimal viable Edge.
TEST_CLASS (Node)
Test class for minimal viable Node.
TEST_CLASS (Model)
Test class for minimal viable Model.
Detailed Description
Testing Namespace for MVP MarkovModel.
Function Documentation
TEST_CLASS() [1/3]
Testing::MVP::MarkovModel::TEST_CLASS (Edge)
Test class for minimal viable Edge.
test default constructor
test linked constructor with two nodes
test AdjustEdge function
test TraverseNode returning RightNode
test LeftNode/RightNode setter
test negative adjustments
Definition at line 27 of file UnitTests.cpp.
            {
            public:
                TEST_METHOD(default_constructor) {
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>;
                    Assert::IsNull(e->LeftNode());
                    Assert::IsNull(e->RightNode());
                    delete e;
                }
                TEST_METHOD(linked_constructor) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    Assert::IsTrue(LeftNode == e->LeftNode());
                    Assert::IsTrue(RightNode == e->RightNode());
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
                TEST_METHOD(AdjustEdge) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    e->AdjustEdge(15);
                    Assert::AreEqual(15ull, e->EdgeWeight());
                    e->AdjustEdge(15);
                    Assert::AreEqual(30ull, e->EdgeWeight());
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
                TEST_METHOD(TraverseNode) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    Assert::IsTrue(RightNode == e->TraverseNode());
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
                TEST_METHOD(set_left_and_right) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    Markov::Edge<unsigned char>* e2 = new Markov::Edge<unsigned char>;
                    e2->SetLeftEdge(LeftNode);
                    e2->SetRightEdge(RightNode);
                    Assert::IsTrue(e1->LeftNode() == e2->LeftNode());
                    Assert::IsTrue(e1->RightNode() == e2->RightNode());
                    delete LeftNode;
                    delete RightNode;
                    delete e1;
                    delete e2;
                }
                TEST_METHOD(negative_adjust) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(LeftNode, RightNode);
                    e->AdjustEdge(15);
                    Assert::AreEqual(15ull, e->EdgeWeight());
                    e->AdjustEdge(-15);
                    Assert::AreEqual(0ull, e->EdgeWeight());
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
            };
References TEST_CLASS().
TEST_CLASS() [2/3]
Testing::MVP::MarkovModel::TEST_CLASS (Model)
Test class for minimal viable Model.
test model constructor for starter node
test import
test export
test random walk
Definition at line 353 of file UnitTests.cpp.
            {
            public:
                TEST_METHOD(model_constructor) {
                    Markov::Model<unsigned char> m;
                    Assert::AreEqual((unsigned char)'\0', m.StarterNode()->NodeValue());
                }
                TEST_METHOD(import_filename) {
                    Markov::Model<unsigned char> m;
                    Assert::IsTrue(m.Import("../MarkovPasswords/Models/2gram.mdl"));
                }
                TEST_METHOD(export_filename) {
                    Markov::Model<unsigned char> m;
                    Assert::IsTrue(m.Export("../MarkovPasswords/Models/testcase.mdl"));
                }
                TEST_METHOD(random_walk) {
                    unsigned char* res = new unsigned char[12 + 5];
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Model<unsigned char> m;
                    Assert::IsTrue(m.Import("../Models/finished2.mdl"));
                    Assert::IsNotNull(m.RandomWalk(&MarsagliaRandomEngine,1,12,res));
                }
            };
References TEST_CLASS().
Referenced by TEST_CLASS().
TEST_CLASS() [3/3]
Testing::MVP::MarkovModel::TEST_CLASS (Node)
Test class for minimal viable Node.
test default constructor
test custom constructor with unsigned char
test link function
test link function
test RandomNext with low values
test RandomNext with 32 bit high values
random next on a node with no follow-ups
random next on a node with no follow-ups
test updateEdges
test updateEdges
test FindVertice
test FindVertice
test FindVertice
Definition at line 117 of file UnitTests.cpp.
            {
            public:
                TEST_METHOD(default_constructor) {
                    Markov::Node<unsigned char>* n = new Markov::Node<unsigned char>();
                    Assert::AreEqual((unsigned char)0, n->NodeValue());
                    delete n;
                }
                TEST_METHOD(uchar_constructor) {
                    Markov::Node<unsigned char>* n = NULL;
                    unsigned char test_cases[] = { 'c', 0x00, 0xff, -32 };
                    for (unsigned char tcase : test_cases) {
                        n = new Markov::Node<unsigned char>(tcase);
                        Assert::AreEqual(tcase, n->NodeValue());
                        delete n;
                    }
                }
                TEST_METHOD(link_left) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = LeftNode->Link(RightNode);
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
                TEST_METHOD(link_right) {
                    Markov::Node<unsigned char>* LeftNode = new Markov::Node<unsigned char>('l');
                    Markov::Node<unsigned char>* RightNode = new Markov::Node<unsigned char>('r');
                    Markov::Edge<unsigned char>* e = new Markov::Edge<unsigned char>(NULL, RightNode);
                    LeftNode->Link(e);
                    Assert::IsTrue(LeftNode == e->LeftNode());
                    Assert::IsTrue(RightNode == e->RightNode());
                    delete LeftNode;
                    delete RightNode;
                    delete e;
                }
                TEST_METHOD(rand_next_low) {
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Edge<unsigned char>* e = src->Link(target1);
                    e->AdjustEdge(15);
                    Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                    Assert::IsTrue(res == target1);
                    delete src;
                    delete target1;
                    delete e;
                }
                TEST_METHOD(rand_next_u32) {
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Edge<unsigned char>* e = src->Link(target1);
                    e->AdjustEdge(1 << 31);
                    Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                    Assert::IsTrue(res == target1);
                    delete src;
                    delete target1;
                    delete e;
                }
                TEST_METHOD(rand_next_choice_1) {
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Node<unsigned char>* target2 = new Markov::Node<unsigned char>('c');
                    Markov::Edge<unsigned char>* e1 = src->Link(target1);
                    Markov::Edge<unsigned char>* e2 = src->Link(target2);
                    e1->AdjustEdge(1);
                    e2->AdjustEdge((unsigned long)(1ull << 31));
                    Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                    Assert::IsNotNull(res);
                    Assert::IsTrue(res == target2);
                    delete src;
                    delete target1;
                    delete e1;
                    delete e2;
                }
                TEST_METHOD(rand_next_choice_2) {
                    Markov::Random::Marsaglia MarsagliaRandomEngine;
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Node<unsigned char>* target2 = new Markov::Node<unsigned char>('c');
                    Markov::Edge<unsigned char>* e1 = src->Link(target1);
                    Markov::Edge<unsigned char>* e2 = src->Link(target2);
                    e2->AdjustEdge(1);
                    e1->AdjustEdge((unsigned long)(1ull << 31));
                    Markov::Node<unsigned char>* res = src->RandomNext(&MarsagliaRandomEngine);
                    Assert::IsNotNull(res);
                    Assert::IsTrue(res == target1);
                    delete src;
                    delete target1;
                    delete e1;
                    delete e2;
                }
                TEST_METHOD(update_edges_count) {
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Node<unsigned char>* target2 = new Markov::Node<unsigned char>('c');
                    Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(src, target1);
                    Markov::Edge<unsigned char>* e2 = new Markov::Edge<unsigned char>(src, target2);
                    e1->AdjustEdge(25);
                    src->UpdateEdges(e1);
                    e2->AdjustEdge(30);
                    src->UpdateEdges(e2);
                    Assert::AreEqual((size_t)2, src->Edges()->size());
                    delete src;
                    delete target1;
                    delete e1;
                    delete e2;
                }
                TEST_METHOD(update_edges_total) {
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Edge<unsigned char>* e1 = new Markov::Edge<unsigned char>(src, target1);
                    Markov::Edge<unsigned char>* e2 = new Markov::Edge<unsigned char>(src, target1);
                    e1->AdjustEdge(25);
                    src->UpdateEdges(e1);
                    e2->AdjustEdge(30);
                    src->UpdateEdges(e2);
                    //Assert::AreEqual(55ull, src->TotalEdgeWeights());
                    delete src;
                    delete target1;
                    delete e1;
                    delete e2;
                }
                TEST_METHOD(find_vertice) {
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Node<unsigned char>* target2 = new Markov::Node<unsigned char>('c');
                    Markov::Edge<unsigned char>* res = NULL;
                    src->Link(target1);
                    src->Link(target2);
                    
                    res = src->FindEdge('b');
                    Assert::IsNotNull(res);
                    Assert::AreEqual((unsigned char)'b', res->TraverseNode()->NodeValue());
                    res = src->FindEdge('c');
                    Assert::IsNotNull(res);
                    Assert::AreEqual((unsigned char)'c', res->TraverseNode()->NodeValue());
                    delete src;
                    delete target1;
                    delete target2;
                }
                TEST_METHOD(find_vertice_without_any) {
                    auto _invalid_next = [] {
                        Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                        Markov::Edge<unsigned char>* res = NULL;
                        res = src->FindEdge('b');
                        Assert::IsNull(res);
                        delete src;
                    };
                    //Assert::ExpectException<std::logic_error>(_invalid_next);
                }
                TEST_METHOD(find_vertice_nonexistent) {
                    Markov::Node<unsigned char>* src = new Markov::Node<unsigned char>('a');
                    Markov::Node<unsigned char>* target1 = new Markov::Node<unsigned char>('b');
                    Markov::Node<unsigned char>* target2 = new Markov::Node<unsigned char>('c');
                    Markov::Edge<unsigned char>* res = NULL;
                    src->Link(target1);
                    src->Link(target2);
                    res = src->FindEdge('D');
                    Assert::IsNull(res);
                    delete src;
                    delete target1;
                    delete target2;
                }
            };
References TEST_CLASS().