markopy Namespace Reference
Functions
def cli_init (str input_model)
def cli_train (markopy.ModelMatrix model, str dataset, str seperator, str output, bool output_forced=False, bool bulk=False)
def cli_generate (markopy.ModelMatrix model, str wordlist, bool bulk=False)
Variables
parser
help
default
action
args = parser.parse_args()
Detailed Description
@package markopy
 @file markopy.py
 @namespace Python::Markopy
 @brief Command line 
 @authors Ata Hakçıl
Function Documentation
cli_generate()
def markopy.cli_generate (markopy.ModelMatrix model, str wordlist, bool bulk = False)
Generate strings from the model
    @param model: model instance
    @param wordlist wordlist filename
    @param bulk marks bulk operation with directories
Definition at line 106 of file markopy.py.
def cli_generate(model : markopy.ModelMatrix, wordlist : str, bulk : bool=False):
    """ Generate strings from the model
        @param model: model instance
        @param wordlist wordlist filename
        @param bulk marks bulk operation with directories
    """
    if not (wordlist or args.count):
        logging.pprint("Generation mode requires -w/--wordlist and -n/--count parameters. Exiting.")
        exit(2)
    
    if(bulk and os.path.isfile(wordlist)):
        logging.pprint(f"{wordlist} exists and will be overwritten.", 1)
    model.Generate(int(args.count), wordlist, int(args.min), int(args.max), int(args.threads))
if(args.bulk):
    logging.pprint(f"Bulk mode operation chosen.", 4)
    if (args.mode.lower() == "train"):
        if (os.path.isdir(args.output) and not os.path.isfile(args.output)) and (os.path.isdir(args.dataset) and not os.path.isfile(args.dataset)):
            corpus_list = os.listdir(args.dataset)
            for corpus in corpus_list:
                model = cli_init(args.input)
                logging.pprint(f"Training {args.input} with {corpus}", 2)
                output_file_name = corpus
                model_extension = ""
                if "." in args.input:
                    model_extension = args.input.split(".")[-1]
                cli_train(model, f"{args.dataset}/{corpus}", args.seperator, f"{args.output}/{corpus}.{model_extension}", output_forced=True, bulk=True)
        else:
            logging.pprint("In bulk training, output and dataset should be a directory.")
            exit(1)
    elif (args.mode.lower() == "generate"):
        if (os.path.isdir(args.wordlist) and not os.path.isfile(args.wordlist)) and (os.path.isdir(args.input) and not os.path.isfile(args.input)):
            model_list = os.listdir(args.input)
            print(model_list)
            for input in model_list:
                logging.pprint(f"Generating from {args.input}/{input} to {args.wordlist}/{input}.txt", 2)
                
                model = cli_init(f"{args.input}/{input}")
                model_base = input
                if "." in args.input:
                    model_base = input.split(".")[1]
                cli_generate(model, f"{args.wordlist}/{model_base}.txt", bulk=True)
        else:
            logging.pprint("In bulk generation, input and wordlist should be directory.")
else:
    model = cli_init(args.input)
    if (args.mode.lower() == "generate"):
        cli_generate(model, args.wordlist)
    elif (args.mode.lower() == "train"):
        cli_train(model, args.dataset, args.seperator, args.output, output_forced=True)
    elif(args.mode.lower() == "combine"):
        cli_train(model, args.dataset, args.seperator, args.output)
        cli_generate(model, args.wordlist)
    else:
        logging.pprint("Invalid mode arguement given.")
        logging.pprint("Accepted modes: 'Generate', 'Train', 'Combine'")
        exit(5)
References cli_init(), and cli_train().
cli_init()
def markopy.cli_init (str input_model)
Initialize the model for CLI interation 
    @param input_model Model filename
Definition at line 45 of file markopy.py.
def cli_init(input_model : str):
    """ Initialize the model for CLI interation
        @param input_model Model filename
    """
    logging.VERBOSITY = 0
    if args.verbosity:
        logging.VERBOSITY = args.verbosity
        logging.pprint(f"Verbosity set to {args.verbosity}.", 2)
    logging.pprint("Initializing model.", 1)
    model = markopy.ModelMatrix()
    logging.pprint("Model initialized.", 2)
    logging.pprint("Importing model file.", 1)
    if(not os.path.isfile(input_model)):
        logging.pprint(f"Model file at {input_model} not found. Check the file path, or working directory")
        exit(1)
    model.Import(input_model)
    logging.pprint("Model imported successfully.", 2)
    return model
Referenced by cli_generate().
cli_train()
def markopy.cli_train (markopy.ModelMatrix model, str dataset, str seperator, str output, bool output_forced = False, bool bulk = False)
Train a model via CLI parameters 
    @param model Model instance
    @param dataset filename for the dataset
    @param seperator seperator used with the dataset
    @param output output filename
    @param output_forced force overwrite
    @param bulk marks bulk operation with directories
Definition at line 68 of file markopy.py.
def cli_train(model : markopy.ModelMatrix, dataset : str, seperator : str, output : str, output_forced : bool=False, bulk : bool=False):
    """ Train a model via CLI parameters
        @param model Model instance
        @param dataset filename for the dataset
        @param seperator seperator used with the dataset
        @param output output filename
        @param output_forced force overwrite
        @param bulk marks bulk operation with directories
    """
    if not (dataset and seperator and (output or not output_forced)):
        logging.pprint(f"Training mode requires -d/--dataset{', -o/--output' if output_forced else''} and -s/--seperator parameters. Exiting.")
        exit(2)
    if(not bulk and not os.path.isfile(dataset)):
        logging.pprint(f"{dataset} doesn't exists. Check the file path, or working directory")
        exit(3)
    if(output and os.path.isfile(output)):
        logging.pprint(f"{output} exists and will be overwritten.",1)
    if(seperator == '\\t'):
        logging.pprint("Escaping seperator.", 3)
        seperator = '\t'
    
    if(len(seperator)!=1):
        logging.pprint(f'Delimiter must be a single character, and "{seperator}" is not accepted.')
        exit(4)
    logging.pprint(f'Starting training.', 3)
    model.Train(dataset,seperator, int(args.threads))
    logging.pprint(f'Training completed.', 2)
    if(output):
        logging.pprint(f'Exporting model to {output}', 2)
        model.Export(output)
    else:
        logging.pprint(f'Model will not be exported.', 1)
Referenced by cli_generate().
Variable Documentation
action
markopy.action
Definition at line 38 of file markopy.py.
args
markopy.args = parser.parse_args()
Definition at line 40 of file markopy.py.
default
markopy.default
Definition at line 34 of file markopy.py.
help
markopy.help
Definition at line 28 of file markopy.py.
parser
markopy.parser
Initial value:
= argparse.ArgumentParser(description="Python wrapper for MarkovPasswords.",
epilog=f, formatter_class=argparse.RawTextHelpFormatter)
Definition at line 14 of file markopy.py.