Markov::Markopy Namespace Reference
CPython module for Markov::API objects.
Namespaces
 CUDA
CPython module for Markov::API::CUDA objects.
Functions
BOOST_PYTHON_MODULE (markopy)
Detailed Description
CPython module for Markov::API objects.
Function Documentation
BOOST_PYTHON_MODULE()
Markov::Markopy::BOOST_PYTHON_MODULE (markopy)
Definition at line 37 of file markopy.cpp.
    {
        bool (Markov::API::MarkovPasswords::*Import)(const char*) = &Markov::Model<char>::Import;
        bool (Markov::API::MarkovPasswords::*Export)(const char*) = &Markov::Model<char>::Export;
        class_<Markov::API::MarkovPasswords>("MarkovPasswords", init<>())
            .def(init<>())
            .def("Train", &Markov::API::MarkovPasswords::Train)
            .def("Generate", &Markov::API::MarkovPasswords::Generate)
            .def("Import", Import, "Import a model file.")
            .def("Export", Export, "Export a model to file.")
        ;
        int (Markov::API::ModelMatrix::*FastRandomWalk)(unsigned long int, const char*, int, int, int, bool)
            = &Markov::API::ModelMatrix::FastRandomWalk;
        class_<Markov::API::ModelMatrix>("ModelMatrix", init<>())
            
            .def(init<>())
            .def("Train", &Markov::API::ModelMatrix::Train)
            .def("Import", &Markov::API::ModelMatrix::Import, "Import a model file.")
            .def("Export", Export, "Export a model to file.")
            .def("ConstructMatrix",&Markov::API::ModelMatrix::ConstructMatrix)
            .def("DumpJSON",&Markov::API::ModelMatrix::DumpJSON)
            .def("FastRandomWalk",FastRandomWalk)
            ;
    };
References Markov::API::ModelMatrix::ConstructMatrix(), Markov::API::ModelMatrix::DumpJSON(), Markov::Model< NodeStorageType >::Export(), Markov::API::ModelMatrix::FastRandomWalk(), Markov::API::MarkovPasswords::Generate(), Markov::API::ModelMatrix::Import(), Markov::Model< NodeStorageType >::Import(), Markov::API::MarkovPasswords::Train(), and Markov::API::ModelMatrix::Train().