name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          python-version: [3.8]
    steps:
    - uses: actions/checkout@v2

    - name: Cache Boost
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: D:\a\
        key: 'win-boost-fullcache-1.71-${{ matrix.python-version }}'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build Boost
      id: boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.71.0
        libraries: program_options python
        platform: x64
        configuration: Release

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
